### ISSUE TITLE
Display the wrong information and select data?

### ISSUE THREAD

**Issue by hoanganh2020** [clockbyte/admobadapter#10]
Hi,

I checked to see, it display the wrong information and select click? When ads loaded, information on listview load more slowly. See picture: http://www.appsvn.com/pic/list_error.jpg

And when use lvMessages.setOnItemClickListener will get wrong data with position.

lvMessages.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            public void onItemClick(AdapterView<?> parent, View view,
                                    int position, long id) {
                Toast.makeText(getApplicationContext(),
                        "Click: " + String.valueOf(position),
                        Toast.LENGTH_LONG).show();
            }
        });

Thanks!

**Comment by clockbyte** [comment]
@hoanganh2020 Hi
What branch do you currently use? Please try the latest. Also please post here a piece of code in which you have set up your AdapterWrapper (I mean such params as first ad position, blocks between ads and so on). I could check it then

**Comment by clockbyte** [comment]
@hoanganh2020 Kindly get the latest from https://github.com/clockbyte/admobadapter/tree/first_adv_index
It should fix your first issue with wrong indices.
On 2nd issue: Your piece of code will show the index of clicked item with ad blocks taken into account.   To show pure (source) index kindly update from latest https://github.com/clockbyte/admobadapter/tree/first_adv_index and try the following code. 
```java
lvMessages.setOnItemClickListener(new AdapterView.OnItemClickListener() {
                                              @Override
                                              public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                                                  final AdmobAdapterCalculator adapterCalc = adapterWrapper.getAdapterCalculator();
                                                  int originalPos = adapterCalc.getOriginalContentPosition(position);
                                                  Toast.makeText(getApplicationContext(),
                                                          "Click: " + String.valueOf(originalPos),
                                                          Toast.LENGTH_SHORT).show();
                                              }
                                          });
```

**AdmobAdapterCalculator** gives you some other transformations with indices, look into the documented code to know more. Also now you are able to inject your own indices logic to adapter wrapper. Just inherit from **AdmobAdapterCalculator** and pass your implementation to the method adapterWrapper.setAdapterCalculator(...). Hope it will help.

**Comment by husni75** [comment]
Help My problem in command  ContentUris.withAppendedId(mCurrentUri,id)));
id change use admodadapter
``` 

public void onListItemClick(ListView listView, View view, int position, long id) {             
if (id >= 0) { // should not happen, but I had a crash with this on PlayStore...
                 Toast.makeText(getActivity().getApplicationContext(),
                         "Position: " + String.valueOf(position)+" ID: " + String.valueOf(id),
                         Toast.LENGTH_SHORT).show();

            startActivity(new Intent(Intent.ACTION_VIEW, ContentUris.withAppendedId(mCurrentUri,id)));
        }

    }`

**Comment by MohaidYouness** [comment]
husni75
check this
https://github.com/clockbyte/admobadapter/wiki/Cookbook#in-case-you-stucked-with-getting-the-correct-itemindex-of-a-source-collection-in-a-listviewrecyclerview-click-handler
