### ISSUE TITLE
Any plans on implementing normal banners instead of NativeExpressAds?

### ISSUE THREAD

**Issue by L4grange** [clockbyte/admobadapter#105]
Hello and thank you for this library!

Since google is dropping support of NativeExpressAds in 15 days, are there any plans of replacing them with normal AdMob Banners, as google recommends?

I'm gonna take a shot at this today, was just wondering how to follow the rest of the library as close as possible. Shall I create a new class "AdMobBannerAdapterWrapper", or a new EAdType to be passed to the `AdmobAdapterWrapper`? Which way would be the closest to the rest of the libraries code?

**Comment by L4grange** [comment]
I've implemented the support for normal Banners using the NativeExpressAds as a guide. I've created A PR, please take a look. #106

**Comment by Shajeel-Afzal** [comment]
Awesome. Hopefully, It will be merged soon so that we can use in our projects. It was much needed.

**Comment by kot331107** [comment]
Guyz, will check it tmw. On vacations right now :) @L4grange thx a lot, you contribution is appreciated much. Could u plz send a link on this "dropping support"? I was out of ads news for a quite long time

**Comment by L4grange** [comment]
@kot331107 No worries, enjoy your vacation :)

In the official docs [here](https://developers.google.com/admob/android/native-express) (and in the firebase AdMob docs) it says on the top:

> The native express ad format is being discontinued. Starting October 23, 2017, you'll no longer be able to create new native express ad units. Existing native express ad units will stop serving ads on March 1, 2018. Please see AdMob Help for more information.

Pointing to [here](https://support.google.com/admob/answer/7527424)

AdMob's official code samples have moved from NativeExpress Ads to normal Banners, thus why I needed to swap NativeExpress with banners in my Apps, since serving will stop on March 1st.

To add banner support I copied the Express package of thelibrary and changed all NativeExpressdViews to normal AdViews. Maybe some code is not needed and can be left out, but I followed the NativeExpress implementation, in order not to break anything. Let me know if you need anything else!

**Comment by Shajeel-Afzal** [comment]
@kot331107 Please merge the PR after reviewing and release the new update of the library. Desperately waiting.

**Comment by L4grange** [comment]
@Shajeel-Afzal until then you can point your build.gradle to my fork, for testing. I would not suggest releasing your app with my fork, but feel free to test using the following:

`compile 'com.github.L4grange:admobadapter:-SNAPSHOT'`

**Comment by Shajeel-Afzal** [comment]
Got it @L4grange! I'll test and report here if I found any issues.

**Comment by kot331107** [comment]
Guyz I've merged changes of @L4grange to the experimental branch with my own minor changes. Will test it a bit, then prepare the next release. Also I'm going to update a Wiki.

**Comment by L4grange** [comment]
@kot331107 Perfect! Thank you very much :)
