### ISSUE TITLE
Functional Requirements

### ISSUE THREAD

**Issue by hoanghiephui** [clockbyte/admobadapter#11]
Dear Clockbyte
I think you should add the CardView, and allows you to set the display size of the NativeExpress.
Ex: Small, Medium, Large.

Thanks!

**Comment by clockbyte** [comment]
Greetings!
Do you mean that I should wrap the NativeExpress into the CardView in the layout xml?

**Comment by hoanghiephui** [comment]
Well, I mean it.

**Comment by hoanghiephui** [comment]
Currently, I see ads that show very slow to make up a gap in the list of contents. I think, you should default to hidden advertising. Only when an ads is loading, the new display in the list.

**Comment by clockbyte** [comment]
Yeah you right. However it is duplicated issue.

**Comment by clockbyte** [comment]
@hoanghiephui  On your first issue about the ads size: 
Kindly get the latest code from branch https://github.com/clockbyte/admobadapter/tree/first_adv_index Hope it will help. You don't need neither **adexpresslistview_item.xml** nor something like CardView to wrap with. Just set the following for your adapter wrapper
```java
        adapterWrapper.setAdSize(new AdSize(AdSize.FULL_WIDTH,150));
        adapterWrapper.setAdsUnitId(getString(R.string.test_admob_express_unit_id));
```
