### ISSUE TITLE
When will be the new version of the library available?

### ISSUE THREAD

**Issue by Shajeel-Afzal** [clockbyte/admobadapter#110]
Hi, 
I want to integrate this library to show Banner Ads in the RecyclerView. 

Please let me know when the new version of the library will be available to integrate via gradle?

Regards
- Shajeel

**Comment by kot331107** [comment]
@Shajeel-Afzal Hi, just released :)

**Comment by Shajeel-Afzal** [comment]
Awesome. Is there any way to buy a coffee or lunch for you? Please add some
option. This library doubled my earnings through native express ads.

**Comment by Shajeel-Afzal** [comment]
@kot331107! I think the README file is not updated. I still see 1.4.5 version. Can you update or tell me the new version here?

**Comment by kot331107** [comment]
@Shajeel-Afzal Updated :)  BTW You could take the latest available version in maven looking on the badge 
[![Maven Central](https://maven-badges.herokuapp.com/maven-central/com.github.clockbyte/admobadapter/badge.svg)](https://maven-badges.herokuapp.com/maven-central/com.github.clockbyte/admobadapter)
it seems to be actual.
On the lunch/coffee ... no way :) please use it for free - it is my best reward. However you could add your app to readme.md (or just tell me the link to your app to add) and tell your friends about this lib :) Thx!
