### ISSUE TITLE
show loading icon or view while loading the Ad

### ISSUE THREAD

**Issue by ahmedgalal** [clockbyte/admobadapter#115]
As per google guidelines, you must show an empty space before the Ad shows to avoid unintentional clicks, so i suggest adding a loading view while loading the Ad, it would make the list looks good without breaking google guidelines.

showing only white space kinda breaks the design.

**Comment by kot331107** [comment]
@ahmedgalal  Plz check the **sampleapp** demo application for instance. We definitely show there a "loading" view while banners are preparing to display. Also see https://github.com/clockbyte/admobadapter/wiki/Cookbook#in-case-you-want-to-wrap-your-ad-blocks-into-a-viewgroup-cardview-framelayout-etc to see how to replace white space with your customized "loading view". I would start investigation from the **sampleapp**.
