### ISSUE TITLE
Ignoring app ID and defaulting to UNIT_ID_DEFAULT_BANNER test ads

### ISSUE THREAD

**Issue by HaydenCampbell** [clockbyte/admobadapter#117]
**Admobadapter version or commit:**
v1.4.6

**Android compileSdkVersion:**
27

**Issue description briefly:**
I can't get the app to display real ads, it seems to be ignoring my app ID in the strings resource and defaulting to String UNIT_ID_DEFAULT_BANNER = "ca-app-pub-7246006002889486/6993938523"; // Google's Test unit ID from the BannerAdPreset class.

**Steps to reproduce:**
You can build the sample app MainActivity_ListView_Banner with your own app ID in the strings resource and it will ignore it and default to Google's Test unit ID.

**Comment by kot331107** [comment]
@HaydenCampbell will check!

**Comment by HaydenCampbell** [comment]
Thanks, that works!
