### ISSUE TITLE
Create custom AdView

### ISSUE THREAD

**Issue by mitsus** [clockbyte/admobadapter#12]
Hi,
firstly compliments for great work!
I've a question. I've follow Google guidelines for create Native ADS [(.](https://github.com/googleads/googleads-mobile-android-examples/blob/master/admob/NativeExample/app/src/main/java/com/google/example/gms/nativeexample/MainActivity.java). 
Now i want use your library for insert this ADS (whith my layout) into my ListView.
I've use as taken from Google Example classes populateContentAdView() and refreshAd(). How can i insert them into your project?

Thanks a lot

**Comment by clockbyte** [comment]
Hi,
Thx! Could you please throw me some link to that Google Example's populateContentAdView() and refreshAd() to get with it shortly? 
Kind regards

**Comment by mitsus** [comment]
Hi,
populateContentAdView() -> [https://github.com/googleads/googleads-mobile-android-examples/blob/master/admob/NativeExample/app/src/main/java/com/google/example/gms/nativeexample/MainActivity.java#L85](url) 

refreshAd() -> [https://github.com/googleads/googleads-mobile-android-examples/blob/master/admob/NativeExample/app/src/main/java/com/google/example/gms/nativeexample/MainActivity.java#L143](url)

**Comment by clockbyte** [comment]
@mitsus At first I wanna warn you that you 're going to use Advanced Native ads which are still in a beta, so it should work but only in a test mode.
If it is OK then kindly do the following steps:
on refreshAd() - kindly look into the [AdmobFetcher.java](https://github.com/clockbyte/admobadapter/blob/first_adv_index/admobadapter/src/main/java/com/clockbyte/admobadapter/AdmobFetcher.java#L174)
Seems to be very similar, yeah? I guess it's already implemented in current lib so you can leave it as is...
on populateAppInstallAdView() / populateContentAdView() please take a look into [AdViewHelper.java](https://github.com/clockbyte/admobadapter/blob/first_adv_index/admobadapter/src/main/java/com/clockbyte/admobadapter/AdViewHelper.java). Code looks very same I suppose but you can simply replace it with populateAppInstallAdView() and  populateContentAdView()  from Examples.

I guess the only important difference with that Examples is @RedBrogdon uses there `MobileAds.initialize(this, ADMOB_APP_ID);` https://developers.google.com/android/reference/com/google/android/gms/ads/MobileAds. Maybe I should do the same...I'll get back to this string after a short investigation.

So you'd start with this [recipe](https://github.com/clockbyte/admobadapter/wiki/Cookbook#the-recipe-1-for-the-listview-scrolling-with-advanced-ads). Perhaps you'll have to improve/change a bit the AdViewHelper.java according to your layout.
Feel free to ask me!

**Comment by mitsus** [comment]
@clockbyte Thanks lot for your support.
Ok. Just anther question...so for customize my Native ADS...i must change your AdViewHelper.java. I must import it on my project? Or i can change it calling some methods?

Thanks

**Comment by clockbyte** [comment]
@mitsus Welcome!
At the moment you have to import it to your project (link **admobadapter** to your project as a separate module) and customize it there. I'm going to refactor a bit later and let overload such a things from client's code (the main idea is to prepare this lib for Gradle distribution). 
The other way for you is to copy to your package and modify only files which you need. For your case (ListView/Advanced Ads)it will probably be the following files (from the latest [branch](https://github.com/clockbyte/admobadapter/tree/first_adv_index/admobadapter)):
AdViewHelper.java (you'd modify it according to your goals)
AdmobAdapterCalculator.java
AdmobAdapterWrapper.java
AdmobAdapterWrapperInterface.java
AdmobFetcher.java
AdmobFetcherBase.java
all the **admobadapter/admobadapter/src/main/res/** contents  (you'd modify *.xml according to your goals)
Also take a look into **admobadapter/admobadapter/build.gradle** to get all necessary references.
