### ISSUE TITLE
Can't use admobadapter with FirebaseRecyclerAdapter

### ISSUE THREAD

**Issue by iam-mhaseeb** [clockbyte/admobadapter#122]
**Admobadapter version or commit: 1.4.6**

**Android compileSdkVersion: 27**

**Issue description briefly: admobadapter wraper can't wrap on FirabaseRecyclerAdapter - It shows type casting error**

**Immediate fix requested**

**private FirebaseRecyclerAdapter<String, DailyQuoteHolder> madapter;
adapterWrapper = new AdmobRecyclerAdapterWrapper(this, testDevicesIds);
        adapterWrapper.setAdapter(madapter);**

**Comment by kot331107** [comment]
@iam-mhaseeb Hi, please see https://github.com/clockbyte/admobadapter/issues/81 
Is it the same?

**Comment by iam-mhaseeb** [comment]
Yes, it's same. Closing it due to duplicate.
