### ISSUE TITLE
Admob blocked my account but the ad is still displayed.

### ISSUE THREAD

**Issue by timemake** [clockbyte/admobadapter#128]
I have implemented this library into one of my apps since it was very hard to implement Native Ad.
In general, using the library is more easier and convenient.
Recently, Google blocked my account and all apps don't show the ad except one that has this library.
I'm not sure where the ad is coming from.
Please let me know why it happened.

**Comment by kot331107** [comment]
Hi! Have u set the release id for ad? понедельник, 08 апреля 2019г., 05:25 +03:00 от timemake  notifications@github.com :

**Comment by timemake** [comment]
I'm not able to check the code on AdMob since it is blocked now. But I checked the source code and it is not the test ad code so I assume I put the release id.

**Comment by timemake** [comment]
I checked my code again and noticed I put this. 

adapterWrapper = new AdmobAdapterWrapper(getActivity(), (String) null, EnumSet.of(EAdType.ADVANCED_INSTALLAPP));

This may be the reason why I saw the ad.
Luckily, my Adsense account is alive again since Google has approved my appeal.

**Comment by kot331107** [comment]
Congrats :)  `(String) null` should be the reason of that evil.

**Comment by timemake** [comment]
Cool, I will remove that. Thanks,
