### ISSUE TITLE
Thank you for the library

### ISSUE THREAD

**Issue by Nickx27** [clockbyte/admobadapter#13]
Hi @clockbyte :,
Thanks for the best library for native ads, also I'd like to know is there any way to load ads in specific indexs.

**Comment by clockbyte** [comment]
@Nickx27 Hi!
welcome! Kindly look at the latest branch https://github.com/clockbyte/admobadapter/tree/first_adv_index, you can set a specific index for first  ad block in a list :)

**Comment by Nickx27** [comment]
Wow, thanks dude, its a great help :+1:  :)

**Comment by clockbyte** [comment]
@Nickx27 sure, working on that :)

**Comment by clockbyte** [comment]
@Nickx27 Please get the latest from the branch https://github.com/clockbyte/admobadapter/tree/experimental. I have fixed this issue there. I should warn you that I've made a lot changes there and you could get some errors after updating but I'm sure that this game is worth the candle :) Also I'm going to make my library Gradle/Maven-linkable soon...

**Comment by Nickx27** [comment]
thanks a bunch @clockbyte  :+1:  :)
