### ISSUE TITLE
Limited to RecyclerView.ViewHolder

### ISSUE THREAD

**Issue by wagaana** [clockbyte/admobadapter#133]
**I cant use it in my recycler view**

**
setAdapter(RecyclerView.Adapter<RecyclerView.ViewHolder> adapter)

but my adapter is

RecyclerView.Adapter<Profiles.ViewHolder>
**

**Comment by kot331107** [comment]
@wagaana https://github.com/clockbyte/admobadapter/issues/81 hopefully it help you. I know this lib could use generics instead, sorry, I have no time to improve it for now

**Comment by wagaana** [comment]
Yes Sir. I got it at last
