### ISSUE TITLE
Native ADS doesn't show

### ISSUE THREAD

**Issue by mitsus** [clockbyte/admobadapter#14]
Hi @clockbyte ,
i've add your project into my app.
I've create a new directory and i've put all admobadapter java files into it. I've add all .xml layout files into my layout directory.
I've created admob AdUnitId for Native ADS using my google accout for my app.
Into my fragment that show the listview i've add this code:

      `
       @Override
        public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
	
	View view = inflater.inflate(R.layout.fragment_sample0, container, false);

	coordinatorLayout = (CoordinatorLayout) view.findViewById(R.id.coordinatorLayout);
	listView = (ListView) view.findViewById(R.id.listView);
	swipeRefreshLayout = (SwipeRefreshLayout) view.findViewById(R.id.swipe_refresh_layout);

	

	spotsList = new ArrayList<HashMap<String, String>>();
	adapter= new SwipeListAdapter(mActivity, spotsList);
	adapterWrapper = new AdmobAdapterWrapper(getActivity());
	adapterWrapper.setAdapter(adapter);
	adapterWrapper.setLimitOfAds(3);
	adapterWrapper.setNoOfDataBetweenAds(5);
	String admobUnitId = getResources().getString(R.string.admob_unit_id);
	adapterWrapper.setAdmobReleaseUnitId(admobUnitId);

	listView.setAdapter(adapterWrapper);
	
	swipeRefreshLayout.setOnRefreshListener(this);

   
	swipeRefreshLayout.post(new Runnable() {
								@Override
								public void run() {
									swipeRefreshLayout.setRefreshing(true);
									.....

								}
							}
	);

	return view;
        }
         `
         private void initUpdateAdsTimer() {
	        updateAdsTimer = new Timer();
	        updateAdsTimer.schedule(new TimerTask() {
		@Override
		public void run() {
			       getActivity().runOnUiThread(new Runnable() {
				       @Override
				        public void run() {
					      adapterWrapper.requestUpdateAd();
				        }
			        });
		    }
	         }, 60*1000, 60*1000);
          }
         
I use my ListView with SwipeRefreshLayout and i've all into an Fragment.

Ok my problem is that i'm not able to see anything...i don't see the native banners or they empty space ... as if there were not null, only the list with the data as it was before.

Where is my error.

Thans a lot for your support

**Comment by mitsus** [comment]
Hi @clockbyte ,
i've just try your sampleapp on my Test Device (Samsung Galaxy S with cyanogenMod 4.4) and it work fine.
I've a doubt. I would not have used a Express UnitId instead of a normal UnitID...so it doesn't work?

**Comment by clockbyte** [comment]
@mitsus Hi again :)
At first you could select Verbose in the logcat while debugging and filter all records by "ads" keyword. then I guess you will be able to see what issue exactly is. 
Also if you are trying to show Advanced Native Ads  (I understood so) then you should take a test UnitId for Advanced Ads (you could find it [here](https://github.com/clockbyte/admobadapter/blob/first_adv_index/admobadapter/src/main/res/values/strings.xml) **test_admob_unit_id**. On the other hand if you are  trying Express Ads then you'll have to use **test_admob_express_unit_id**. Please find the example suitable for you into the [MainActivity_ListView.java](https://github.com/clockbyte/admobadapter/blob/first_adv_index/sampleapp/src/main/java/com/clockbyte/admobadapter/sampleapp/MainActivity_ListView.java) for Advanced or [MainActivity_ListView_Express.java](https://github.com/clockbyte/admobadapter/blob/first_adv_index/sampleapp/src/main/java/com/clockbyte/admobadapter/sampleapp/express/MainActivity_ListView_Express.java) for Express

**Comment by mitsus** [comment]
Thanka a lot @clockbyte . Tonight i try there different approach and inform you. Please doesn't close this ticket. Tonight i reply with my tests.

Thank

**Comment by clockbyte** [comment]
@mitsus sure! Waiting for your results. And please don't spend the night coding, take care of your eyes :)

**Comment by mitsus** [comment]
Hi @clockbyte thank you for support. Now all work fine Express and Normal ADS.
I See another problem, but i must open another topic (it id out of it).
Please yuo can close this.
