### ISSUE TITLE
Black background when ADS refresh

### ISSUE THREAD

**Issue by mitsus** [clockbyte/admobadapter#15]
Hi @clockbyte,
i've use for my app your library with Express Native ADS.
All work fine, bu whe it start refreshing (every 30 secs)  i see that items of my listview (TextView, ImageView) became with black background.
If i scroll listview  everything returns fine
It leave it only when start new update, but after that black background returns
Please see screenshot attached
![device-2016-07-08-234243](https://cloud.githubusercontent.com/assets/5763982/16702814/d133fa9c-4568-11e6-943e-558e9cf5c10e.png)

**Comment by clockbyte** [comment]
@mitsus Hi! 
try to add this attribute to your ListView in xml:
```xml
<ListView 
...
android:cacheColorHint="#00000000"
/>
```
Also please clarify if the sampleapp has the same artefacts? Set the tag <activity> in **sampleapp/src/main/AndroidManifest.xml** to the 
<activity
            android:name=".express.MainActivity_ListView_Express"
            android:label="@string/app_name" >
and run it on your test device to check it...

KR

**Comment by mitsus** [comment]
Hi @clockbyte,
attibute don't resolve the problem.
I've try with your sample app...and it is the same, please see picture attachment (yous sampleapp screenhot)
![device-2016-07-11-002156](https://cloud.githubusercontent.com/assets/5763982/16716480/b6232872-46fd-11e6-827c-1895a649bd07.png)

**Comment by clockbyte** [comment]
Hi!
I see...What's device's model and the Android version? Any custom build?

**Comment by mitsus** [comment]
Device is a Samsung Galaxy S Plus with CyanogenMod 4.4.
Do you think that this is the problem?

**Comment by clockbyte** [comment]
I guess the Cyanogen's themes could be the reason but I'm not pretty sure...I have no such artifacts on the listview items on all of my test devices (I haven't any device with Cyanogen). I guess you should look for a solution in this direction. I'll try to find something too.

**Comment by mitsus** [comment]
Hi @clockbyte,
i've buy a new smartphone without cyanogen and all work fine. I think that this ais a cyanogen mod problen so.
If you want you can close this Issue.
Thanks a lot for support
