### ISSUE TITLE
Native ADS Express dynamic Size

### ISSUE THREAD

**Issue by mitsus** [clockbyte/admobadapter#16]
Hi,
i've implemented successfully your library, but just last problem that i tried to solve without success.
In differents screen sizes i'm able to load only a fixed size for my native express ads. I tried also to force dynamic size from code, but i've an error that tell me to use only AdSize from XML.

Cam someone hel me please?

Thanks

**Comment by clockbyte** [comment]
Hi

You're right! There's some kind of bug that blocks when you set the size from code. trying to get with it.

**Comment by clockbyte** [comment]
Kindly get the latest from branch https://github.com/clockbyte/admobadapter/tree/first_adv_index Hope it will help. You don't need **adexpresslistview_item.xml** anymore. Just set the following for your adapter wrapper
```java
        adapterWrapper.setAdSize(new AdSize(AdSize.FULL_WIDTH,150));
        adapterWrapper.setAdsUnitId(getString(R.string.test_admob_express_unit_id));
```

**Comment by Dinesh-Sunny** [comment]
Hello @clockbyte !

Test ads are displaying fine. But I am facing lot of difficulty to display real ads! I have real Native Ad sized 360x132 dp.

and also 

`adapterWrapper = new AdmobRecyclerAdapterWrapper(
                this, getResources().getString(R.string.test_admob_express_unit_id));`

This code will never work, where as 

`adapterWrapper = new AdmobRecyclerAdapterWrapper(
                this, testDevicesIds);`

will work but only shows test ads.

P.s: I replaced test_admob_app_id and test_admob_express_unit_id in my strings resource file with working(tested) app id and unit id. 

are these methods 
`adapterWrapper.setAdSize(new AdSize(AdSize.FULL_WIDTH,150));
       adapterWrapper.setAdsUnitId(getString(R.string.test_admob_express_unit_id));`

available in RecyclerView too? or plz guide me how to do this

**Comment by clockbyte** [comment]
@Dinesh-Sunny Hi
What version do you use?
I use `adapterWrapper = new AdmobRecyclerAdapterWrapper( this, <admobReleaseUnitId>)` for my release branch and it works good. But there aren't many real ads there yet so it could duplicate.

**Comment by Dinesh-Sunny** [comment]
HI..
I Use the latest version 1.2.

And about duplicacy of ads. I use admob native ads of size 360x132 dp which is smaller than the test ads. Real ads are not displaying only test ads being displayed.

It would be better if we have below methods for RecyclerViewList too
`adapterWrapper.setAdSize(new AdSize(AdSize.FULL_WIDTH,150)); adapterWrapper.setAdsUnitId(getString(R.string.test_admob_express_unit_id));`

**Comment by clockbyte** [comment]
@Dinesh-Sunny Hi

I can't realize how I can provide to you these methods for RecyclerView :) And what should they do then?

**Comment by Dinesh-Sunny** [comment]
@clockbyte Yes! I think you are right we already have multiple constructors of AdmobRecyclerAdapterWrapper which satisfy.

I am getting this error 
There was a problem getting an ad response. ErrorCode: 0
Failed to load ad: 0

But I tested this app id and unit id seperately in an activity which displaying real ads.
But when i insert into this `adapterWrapper = new AdmobRecyclerAdapterWrapper( this, <admobReleaseUnitId>)` it is giving me the above error

Thank you for your quick reply :)

**Comment by clockbyte** [comment]
@Dinesh-Sunny I've updated my comment a bit :)

**Comment by Dinesh-Sunny** [comment]
@clockbyte **No luck till now!**

Tried everything from docs but coudn't get real ads apart from test ads. Checked source code too

Logcat:
`/com.iconicskill.lettertopicture I/com.clockbyte.admobadapter.AdmobFetcher: Fetching Ad now`
`/com.iconicskill.lettertopicture I/com.clockbyte.admobadapter.AdmobFetcher: onAdFailedToLoad 0`

**Here is my ManiActivity:**

package com.iconicskill.lettertopicture;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;

import com.clockbyte.admobadapter.AdmobRecyclerAdapterWrapper;
import com.google.android.gms.ads.AdRequest;
import com.google.android.gms.ads.MobileAds;
import com.iconicskill.adapter.CustomRvAdapter;

import java.util.ArrayList;


public class MainActivity extends AppCompatActivity {

    RecyclerView rv;
    ArrayList<Integer> imageArray;
    AdmobRecyclerAdapterWrapper helperAdapter;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        imageArray = new ArrayList<>();
        imageArray.add(R.drawable.ant);
        imageArray.add(R.drawable.bird);
        imageArray.add(R.drawable.cat);
        imageArray.add(R.drawable.dinosaur);
        imageArray.add(R.drawable.elephant);
        imageArray.add(R.drawable.fish);
        imageArray.add(R.drawable.giraffe);
        imageArray.add(R.drawable.horse);
        imageArray.add(R.drawable.icecream);
        imageArray.add(R.drawable.jug);
        imageArray.add(R.drawable.key);
        imageArray.add(R.drawable.lamp);
        imageArray.add(R.drawable.mouse);
        imageArray.add(R.drawable.net);
        imageArray.add(R.drawable.octopus);
        imageArray.add(R.drawable.penguin);
        imageArray.add(R.drawable.qween);
        imageArray.add(R.drawable.robot);
        imageArray.add(R.drawable.swan);
        imageArray.add(R.drawable.tent);
        imageArray.add(R.drawable.umbrella);
        imageArray.add(R.drawable.vulture);
        imageArray.add(R.drawable.watermelon);
        imageArray.add(R.drawable.xray);
        imageArray.add(R.drawable.yak);
        imageArray.add(R.drawable.zebra);

        MobileAds.initialize(this, "ca-app-pub-8738xxxxxxxxxxxx~xxxxxxxxxx");

        rv = (RecyclerView) findViewById(R.id.recyclerView);
        rv.setLayoutManager(new LinearLayoutManager(this));


        attachNativeAds();

    }

    private void attachNativeAds() {
        String[] testDevicesIds = new String[]{
                "D7C62FAE719398E5BB10xxxxxxxxxxxx",
                AdRequest.DEVICE_ID_EMULATOR};

        CustomRvAdapter adapter = new CustomRvAdapter(this);
        //        helperAdapter = new AdmobRecyclerAdapterWrapper(
        //                this, "ca-app-pub-3940256099942544/6300978111");

        helperAdapter = new AdmobRecyclerAdapterWrapper(
                    this, "ca-app-pub-3940256099942544/6300978111");  //this one native test ad id

        helperAdapter.setAdapter(adapter);


        helperAdapter.setLimitOfAds(3);

        helperAdapter.setNoOfDataBetweenAds(6);

        helperAdapter.setFirstAdIndex(2);


        rv.setAdapter(helperAdapter);

        adapter.addAll(imageArray);
        adapter.notifyDataSetChanged();

    }


}

**Comment by clockbyte** [comment]
@Dinesh-Sunny 
Ha-ha I see:)  Sorry, I have thought that you trying to show express ads. Seems advanced ads are still in Beta release at the moment. Kindly use **AdmobExpressRecyclerAdapterWrapper** instead and look into Recipe 3 in our Wiki.

**Comment by Dinesh-Sunny** [comment]
I will try @clockbyte Thanks for your support!

I am also thinking to contribute to this repo :)
