### ISSUE TITLE
Native ads admob or facebook into RecyclerView .

### ISSUE THREAD

**Issue by hoanghiephui** [clockbyte/admobadapter#2]
I enjoyed your tutorials. I hope you do a tutorial on integrating Native ads admob or facebook into RecyclerView .

Thanks,

Regards

**Comment by clockbyte** [comment]
Hi, glad to hear you find this stuff useful :) I'll try to expand this lib with the RecyclerView soon I guess.

Kind Regards

**Comment by clockbyte** [comment]
The support for the RecyclerViewer was added due to the commit [6014f88](https://github.com/clockbyte/admobadapter/commit/6014f88ead0ab2d94d366ca14a159cce3ad12230) Please take a look into the sample app and to the Readme to get some quick start there :)

**Comment by hoanghiephui** [comment]
Woa....thanks you very muck. Good!
