### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by hoanghiephui** [clockbyte/admobadapter#20]
Dear Clockbyte
My application crash when I exit the app. Please see attached image
![screenshot 1](https://cloud.githubusercontent.com/assets/10971659/17829106/94e69c30-66cd-11e6-87fa-1126830ac21a.png)

**Comment by hoanghiephui** [comment]
I've fixed it, by changing the source code location.

in methods "destroyAllAds()" in class AdmobFetcherBase.

change mContext.clear(); down to notifyObserversOfAdSizeChange(-1);

**Comment by clockbyte** [comment]
Dear @hoanghiephui 
Yeah thx a lot! I've just fixed it in the commit https://github.com/clockbyte/admobadapter/commit/9d5784b4730dd4d5470de6796d5082f753dcf04f

**Comment by Dinesh-Sunny** [comment]
It still exists!
