### ISSUE TITLE
How to use getOriginalContentPosition

### ISSUE THREAD

**Issue by technohowl** [clockbyte/admobadapter#21]
Hi,

Usage guide says to call `int originalPos = adapterCalc.getOriginalContentPosition(position);` to get the correct index of the data in the adapter.

But, I find the function used in the library to have 2 more parameters.         
    `public int getOriginalContentPosition(int position, int fetchedAdsCount, int sourceItemsCount)`

Can you update the usage example and guide.

**Comment by clockbyte** [comment]
Hi,

You right. Thx. Let me recall and I'll back to you.

Regards

**Comment by technohowl** [comment]
Hi, Thanks.
It seems the position is not returned correctly, it is confirmed from the logs.

> 08-29 23:52:35.353 23368-23368/ E/app: adapter po:0 > original po:0
08-29 23:52:40.855 23368-23368/ E/app: adapter po:1 > original po:1
08-29 23:52:43.280 23368-23368/ E/app: **adapter po:2 > original po:1**
08-29 23:52:45.624 23368-23368/ E/app: adapter po:3 > original po:2
08-29 23:52:47.338 23368-23368/ E/app: adapter po:4 > original po:3
08-29 23:52:51.197 23368-23368/ E/app: adapter po:8 > original po:7

I had set first index to 2 and limit of ads to 3.

**Comment by technohowl** [comment]
Hey,

Is there a way to find the opposite i.e from original to wrapper position?

**Comment by clockbyte** [comment]
@technohowl actually the answer is no :) Do you need it?

**Comment by technohowl** [comment]
The scenario is I have to catch click event from the button which is inside the list row. The `position`  that I get in my interface is the original position.

**Comment by clockbyte** [comment]
@technohowl I'll try to add this feature asap.

**Comment by clockbyte** [comment]
@technohowl 
Finally I've added it. See 
`public int translateSourceIndexToWrapperPosition(int sourcePos, int fetchedAdsCount) `
in **AdmobAdapterCalculator.java**. You could get the **fetchedAdsCount** as shown in the previous sample. Hope it  will help.

**Comment by technohowl** [comment]
Hey @clockbyte thanks a lot. 
Not urgent. I would take the changes from the master.  :)
