### ISSUE TITLE
Ads show the wrong location

### ISSUE THREAD

**Issue by hoanghiephui** [clockbyte/admobadapter#22]
Dear Clockbyte
I'm having a problem, as though I had sets the first ad block index  in the adapter equal 2, but an ad has been replaced in the first place, to lose one of my item in adapter. 

You can see me, and how to overcome it?
![device-2016-09-04-103352](https://cloud.githubusercontent.com/assets/10971659/18228871/1e128514-728b-11e6-92f0-2ed3b071da77.png)

**Comment by clockbyte** [comment]
@hoanghiephui please describe here all the parameters to reproduce it. I need to know what you set in the following methods:  
adapterWrapper.setLimitOfAds(3);
adapterWrapper.setNoOfDataBetweenAds(10);
adapterWrapper.setFirstAdIndex(2);

Also how many items in the source collections were at that moment? Do you publish items  asyncronously (not all at the moment)?
**and please clarify do you use the latest version of Admobadapter (in maven-central it is 1.2.4)?**

**Comment by hoanghiephui** [comment]
Yes, I have set up as what you have instructions

"adapterWrapper.setLimitOfAds(3);
adapterWrapper.setNoOfDataBetweenAds(10);
adapterWrapper.setFirstAdIndex(2);"

And i use the latest version.

**Comment by hoanghiephui** [comment]
**My Adapter**
`import android.animation.Animator;
import android.animation.AnimatorListenerAdapter;
import android.animation.ObjectAnimator;
import android.animation.ValueAnimator;
import android.annotation.SuppressLint;
import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.graphics.ColorMatrixColorFilter;
import android.graphics.drawable.Drawable;
import android.os.Build;
import android.support.v4.app.ActivityCompat;
import android.support.v4.app.ActivityOptionsCompat;
import android.support.v4.util.Pair;
import android.support.v7.widget.RecyclerView;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageButton;
import android.widget.RelativeLayout;
import android.widget.TextView;

import com.bumptech.glide.Glide;
import com.bumptech.glide.load.engine.DiskCacheStrategy;
import com.bumptech.glide.load.resource.drawable.GlideDrawable;
import com.bumptech.glide.request.RequestListener;
import com.bumptech.glide.request.target.Target;
import com.unsplash.wallsplash.R;
import com.unsplash.wallsplash.WallSplashApplication;
import com.unsplash.wallsplash._common.data.data.Collection;
import com.unsplash.wallsplash._common.data.data.LikePhotoResult;
import com.unsplash.wallsplash._common.data.data.Me;
import com.unsplash.wallsplash._common.data.data.Photo;
import com.unsplash.wallsplash._common.data.service.PhotoService;
import com.unsplash.wallsplash._common.data.tools.AuthManager;
import com.unsplash.wallsplash._common.ui.activity.LoginActivity;
import com.unsplash.wallsplash._common.ui.dialog.SelectCollectionDialog;
import com.unsplash.wallsplash._common.ui.widget.FreedomImageView;
import com.unsplash.wallsplash._common.utils.AnimUtils;
import com.unsplash.wallsplash._common.utils.ColorUtils;
import com.unsplash.wallsplash._common.utils.ObservableColorMatrix;
import com.unsplash.wallsplash._common.utils.TypefaceUtils;
import com.unsplash.wallsplash.me.view.activity.MeActivity;
import com.unsplash.wallsplash.photo.view.activity.PhotoActivity;

import java.util.List;

import retrofit2.Call;
import retrofit2.Response;

/**
 * Photos adapter. (Recycler view)
 */

public class PhotoAdapter extends RecyclerView.Adapter<RecyclerView.ViewHolder>
        implements SelectCollectionDialog.OnCollectionsChangedListener {
    // widget
    private Context a;
    private List<Photo> itemList;
    private PhotoService service;

    // data
    private boolean own = false;

    /**
     * <br> life cycle.
     */

    public PhotoAdapter(Context a, List<Photo> list) {
        this.a = a;
        this.itemList = list;
    }

    /**
     * <br> UI.
     */

    @Override
    public ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        View v = LayoutInflater.from(parent.getContext()).inflate(R.layout.item_photo, parent, false);
        return new ViewHolder(v, viewType);
    }



    @SuppressLint("RecyclerView")
    @Override
    public void onBindViewHolder(final RecyclerView.ViewHolder holder1, final int position) {
        final ViewHolder holder = (ViewHolder)holder1;
        holder.title.setText("");
        holder.image.setShowShadow(false);
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.LOLLIPOP) {
            Glide.with(a)
                    .load(itemList.get(position).urls.regular)
                    .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                    .listener(new RequestListener<String, GlideDrawable>() {
                        @Override
                        public boolean onResourceReady(GlideDrawable resource, String model,
                                                       Target<GlideDrawable> target,
                                                       boolean isFromMemoryCache, boolean isFirstResource) {
                            itemList.get(position).loadPhotoSuccess = true;
                            String titleTxt = "By " + itemList.get(position).user.name + ", On "
                                    + itemList.get(position).created_at.split("T")[0];
                            holder.title.setText(titleTxt);
                            holder.image.setShowShadow(true);
                            return false;
                        }

                        @Override
                        public boolean onException(Exception e, String model,
                                                   Target<GlideDrawable> target,
                                                   boolean isFirstResource) {
                            return false;
                        }
                    })
                    .into(holder.image);
        } else {
            Glide.with(a)
                    .load(itemList.get(position).urls.regular)
                    .listener(new RequestListener<String, GlideDrawable>() {
                        @Override
                        public boolean onResourceReady(GlideDrawable resource, String model,
                                                       Target<GlideDrawable> target,
                                                       boolean isFromMemoryCache, boolean isFirstResource) {
                            itemList.get(position).loadPhotoSuccess = true;
                            if (!itemList.get(position).hasFadedIn) {
                                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN) {
                                    holder.image.setHasTransientState(true);
                                }
                                final ObservableColorMatrix matrix = new ObservableColorMatrix();
                                final ObjectAnimator saturation = ObjectAnimator.ofFloat(
                                        matrix, ObservableColorMatrix.SATURATION, 0f, 1f);
                                saturation.addUpdateListener(new ValueAnimator.AnimatorUpdateListener
                                        () {
                                    @Override
                                    public void onAnimationUpdate(ValueAnimator valueAnimator) {
                                        // just animating the color matrix does not invalidate the
                                        // drawable so need this update listener.  Also have to create a
                                        // new CMCF as the matrix is immutable :(
                                        holder.image.setColorFilter(new ColorMatrixColorFilter(matrix));
                                    }
                                });
                                saturation.setDuration(2000L);
                                saturation.setInterpolator(AnimUtils.getFastOutSlowInInterpolator(a));
                                saturation.addListener(new AnimatorListenerAdapter() {
                                    @Override
                                    public void onAnimationEnd(Animator animation) {
                                        holder.image.clearColorFilter();
                                        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN) {
                                            holder.image.setHasTransientState(false);
                                        }
                                    }
                                });
                                saturation.start();
                                itemList.get(position).hasFadedIn = true;
                            }
                            String titleTxt = "By " + itemList.get(position).user.name + ", On "
                                    + itemList.get(position).created_at.split("T")[0];
                            holder.title.setText(titleTxt);
                            holder.image.setShowShadow(true);
                            return false;
                        }

                        @Override
                        public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) {
                            return false;
                        }
                    })
                    .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                    .into(holder.image);
        }

        if (itemList.get(position).liked_by_user) {
            holder.likeButton.setImageResource(R.drawable.ic_item_heart_red);
        } else {
            holder.likeButton.setImageResource(R.drawable.ic_item_heart_outline);
        }

        holder.background.setBackgroundColor(
                ColorUtils.calcCardBackgroundColor(
                        a,
                        itemList.get(position).color));

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            holder.image.setTransitionName(itemList.get(position).id);
        }
    }

    @Override
    public void onViewRecycled(RecyclerView.ViewHolder holder1) {
        ViewHolder holder = (ViewHolder)holder1;
        Glide.clear((holder.image));
    }

    public void setActivity(Activity a) {
        this.a = a;
    }

    /**
     * <br> data.
     */

    @Override
    public int getItemCount() {
        return itemList.size();
    }

    @Override
    public int getItemViewType(int position) {
        return position;
    }

    public void insertItem(Photo item) {
        itemList.add(item);
        notifyItemInserted(itemList.size() - 1);
    }

    public void clearItem() {
        itemList.clear();
        notifyDataSetChanged();
    }

    private void setLikeForAPhoto(int position) {
        if (service == null) {
            service = PhotoService.getService();
        } else {
            service.cancel();
        }
        service.setLikeForAPhoto(
                itemList.get(position).id,
                !itemList.get(position).liked_by_user,
                new OnSetLikeListener(position));
    }

    public void cancelService() {
        if (service != null) {
            service.cancel();
        }
    }

    public int getRealItemCount() {
        return itemList.size();
    }

    public void setOwn(boolean own) {
        this.own = own;
    }

    /**
     * <br> interface.
     */

    // on set like listener.

    private class OnSetLikeListener implements PhotoService.OnSetLikeListener {
        // data
        private int position;

        public OnSetLikeListener(int position) {
            this.position = position;
        }

        @Override
        public void onSetLikeSuccess(Call<LikePhotoResult> call, Response<LikePhotoResult> response) {
            if (response.body() != null
                    && itemList.size() >= position && itemList.get(position).id.equals(response.body().photo.id)) {
                itemList.get(position).liked_by_user = response.body().photo.liked_by_user;
                itemList.get(position).likes = response.body().photo.likes;
            }
        }

        @Override
        public void onSetLikeFailed(Call<LikePhotoResult> call, Throwable t) {
            // do nothing.
        }
    }

    // on collections changed listener.

    @Override
    public void onAddCollection(Collection c) {
        ((MeActivity) a).addCollection(c);
    }

    @Override
    public void onAddPhotoToCollection(Collection c, Me me) {
        ((MeActivity) a).changeCollection(c);
    }

    /**
     * <br> inner class.
     */

    // view holder.

    public class ViewHolder extends RecyclerView.ViewHolder
            implements View.OnClickListener {
        // widget
        public RelativeLayout background;
        public FreedomImageView image;
        public TextView title;
        public ImageButton likeButton;

        public ViewHolder(View itemView, int position) {
            super(itemView);

            this.background = (RelativeLayout) itemView.findViewById(R.id.item_photo_background);
            background.setOnClickListener(this);

            this.image = (FreedomImageView) itemView.findViewById(R.id.item_photo_image);
            image.setSize(itemList.get(position).width, itemList.get(position).height);

            this.title = (TextView) itemView.findViewById(R.id.item_photo_title);
            TypefaceUtils.setTypeface(itemView.getContext(), title);

            this.likeButton = (ImageButton) itemView.findViewById(R.id.item_photo_likeButton);
            likeButton.setOnClickListener(this);

            itemView.findViewById(R.id.item_photo_collectionButton).setOnClickListener(this);
        }

        @Override
        public void onClick(View view) {
            switch (view.getId()) {
                case R.id.item_photo_background:
                    if (a instanceof Activity) {
                        Photo p = itemList.get(getAdapterPosition());
                        WallSplashApplication.getInstance().setPhoto(p);

                        if (itemList.get(getAdapterPosition()).loadPhotoSuccess) {
                            View imageView = ((RelativeLayout) view).getChildAt(0);
                            Drawable d = ((FreedomImageView) imageView).getDrawable();
                            WallSplashApplication.getInstance().setDrawable(d);
                        } else {
                            WallSplashApplication.getInstance().setDrawable(null);
                        }

                        Intent intent = new Intent(a, PhotoActivity.class);
                        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.LOLLIPOP) {
                            ActivityOptionsCompat options = ActivityOptionsCompat
                                    .makeScaleUpAnimation(
                                            view,
                                            (int) view.getX(), (int) view.getY(),
                                            view.getMeasuredWidth(), view.getMeasuredHeight());
                            ActivityCompat.startActivity((Activity) a, intent, options.toBundle());
                        } else {
                            View imageView = ((RelativeLayout) view).getChildAt(0);
                            ActivityOptionsCompat options = ActivityOptionsCompat
                                    .makeSceneTransitionAnimation(
                                            (Activity) a,
                                            Pair.create(imageView, a.getString(R.string.transition_photo_image)),
                                            Pair.create(imageView, a.getString(R.string.transition_photo_background)));
                            ActivityCompat.startActivity((Activity) a, intent, options.toBundle());
                        }
                    }
                    break;

                case R.id.item_photo_likeButton:
                    if (!AuthManager.getInstance().isAuthorized()) {
                        Intent i = new Intent(a, LoginActivity.class);
                        a.startActivity(i);
                    } else {
                        setLikeForAPhoto(getAdapterPosition());
                        if (itemList.get(getAdapterPosition()).liked_by_user) {
                            itemList.get(getAdapterPosition()).liked_by_user = false;
                            ((ImageButton) view).setImageResource(R.drawable.ic_item_heart_broken);
                        } else {
                            itemList.get(getAdapterPosition()).liked_by_user = true;
                            ((ImageButton) view).setImageResource(R.drawable.ic_item_heart_red);
                        }
                    }
                    break;

                case R.id.item_photo_collectionButton:
                    if (a instanceof Activity) {
                        if (!AuthManager.getInstance().isAuthorized()) {
                            Intent i = new Intent(a, LoginActivity.class);
                            a.startActivity(i);
                        } else {
                            SelectCollectionDialog dialog = new SelectCollectionDialog();
                            dialog.setPhoto(itemList.get(getAdapterPosition()));
                            if (own) {
                                dialog.setOnCollectionsChangedListener(PhotoAdapter.this);
                            }
                            dialog.show(((Activity) a).getFragmentManager(), null);
                        }
                    }
                    break;
            }
        }
    }
}`

**And View**

`import android.annotation.SuppressLint;
import android.app.Activity;
import android.content.Context;
import android.support.v4.content.ContextCompat;
import android.support.v4.view.ViewCompat;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.view.LayoutInflater;
import android.view.View;
import android.widget.Button;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.RelativeLayout;
import android.widget.TextView;

import com.bumptech.glide.Glide;
import com.clockbyte.admobadapter.expressads.AdmobExpressRecyclerAdapterWrapper;
import com.github.rahatarmanahmed.cpv.CircularProgressView;
import com.google.android.gms.ads.AdRequest;
import com.unsplash.wallsplash.R;
import com.unsplash.wallsplash._common.i.model.LoadModel;
import com.unsplash.wallsplash._common.i.model.PhotosModel;
import com.unsplash.wallsplash._common.i.model.ScrollModel;
import com.unsplash.wallsplash._common.i.presenter.LoadPresenter;
import com.unsplash.wallsplash._common.i.presenter.PagerPresenter;
import com.unsplash.wallsplash._common.i.presenter.PhotosPresenter;
import com.unsplash.wallsplash._common.i.presenter.ScrollPresenter;
import com.unsplash.wallsplash._common.i.view.LoadView;
import com.unsplash.wallsplash._common.i.view.PagerView;
import com.unsplash.wallsplash._common.i.view.PhotosView;
import com.unsplash.wallsplash._common.i.view.ScrollView;
import com.unsplash.wallsplash._common.ui.widget.swipeRefreshLayout.BothWaySwipeRefreshLayout;
import com.unsplash.wallsplash._common.utils.AnimUtils;
import com.unsplash.wallsplash._common.utils.BackToTopUtils;
import com.unsplash.wallsplash._common.utils.ThemeUtils;
import com.unsplash.wallsplash.main.model.widget.LoadObject;
import com.unsplash.wallsplash.main.model.widget.PhotosObject;
import com.unsplash.wallsplash.main.model.widget.ScrollObject;
import com.unsplash.wallsplash.main.presenter.widget.LoadImplementor;
import com.unsplash.wallsplash.main.presenter.widget.PagerImplementor;
import com.unsplash.wallsplash.main.presenter.widget.PhotosImplementor;
import com.unsplash.wallsplash.main.presenter.widget.ScrollImplementor;

/**
 * Home photos view.
 */

@SuppressLint("ViewConstructor")
public class HomePhotosView extends FrameLayout
        implements PhotosView, PagerView, LoadView, ScrollView,
        View.OnClickListener, BothWaySwipeRefreshLayout.OnRefreshAndLoadListener {
    // model.
    private PhotosModel photosModel;
    private LoadModel loadModel;
    private ScrollModel scrollModel;

    // view.
    private CircularProgressView progressView;
    private RelativeLayout feedbackContainer;
    private TextView feedbackText;

    private BothWaySwipeRefreshLayout refreshLayout;
    private RecyclerView recyclerView;
    private AdmobExpressRecyclerAdapterWrapper adapterWrapper;

    // presenter.
    private PhotosPresenter photosPresenter;
    private PagerPresenter pagerPresenter;
    private LoadPresenter loadPresenter;
    private ScrollPresenter scrollPresenter;
    /**
     * <br> life cycle.
     */



    public HomePhotosView(Activity a, int photosType) {
        super(a);
        this.initialize(a, photosType);
    }

    @SuppressLint("InflateParams")
    private void initialize(Activity a, int photosType) {
        View loadingView = LayoutInflater.from(getContext()).inflate(R.layout.container_loading_view_large, null, false);
        addView(loadingView);

        View contentView = LayoutInflater.from(getContext()).inflate(R.layout.container_photo_list, null, false);
        addView(contentView);

        initModel(a, photosType);
        initView();
        initPresenter();
    }

    /**
     * <br> presenter.
     */

    private void initPresenter() {
        this.photosPresenter = new PhotosImplementor(photosModel, this);
        this.pagerPresenter = new PagerImplementor(this);
        this.loadPresenter = new LoadImplementor(loadModel, this);
        this.scrollPresenter = new ScrollImplementor(scrollModel, this);
    }

    /**
     * <br> view.
     */

    private void initView() {
        this.initContentView();
        this.initLoadingView();
    }

    private void initContentView() {
        this.refreshLayout = (BothWaySwipeRefreshLayout) findViewById(R.id.container_photo_list_swipeRefreshLayout);
        refreshLayout.setOnRefreshAndLoadListener(this);
        refreshLayout.setVisibility(GONE);
        if (ThemeUtils.getInstance(getContext()).isLightTheme()) {
            refreshLayout.setColorSchemeColors(ContextCompat.getColor(getContext(), R.color.colorWhite));
            refreshLayout.setProgressBackgroundColorSchemeResource(R.color.colorPrimary_light);
        } else {
            refreshLayout.setColorSchemeColors(ContextCompat.getColor(getContext(), R.color.colorTextContent_dark));
            refreshLayout.setProgressBackgroundColorSchemeResource(R.color.colorPrimary_dark);
        }

        this.recyclerView = (RecyclerView) findViewById(R.id.container_photo_list_recyclerView);
        String[] testDevicesIds = new String[]{getContext().getString(R.string.testDeviceID), AdRequest.DEVICE_ID_EMULATOR};
        adapterWrapper = new AdmobExpressRecyclerAdapterWrapper(getContext(), testDevicesIds);
        adapterWrapper.setAdapter(photosModel.getAdapter());
        adapterWrapper.setLimitOfAds(3);
        adapterWrapper.setNoOfDataBetweenAds(10);
        adapterWrapper.setFirstAdIndex(2);
        recyclerView.setAdapter(adapterWrapper);
        //recyclerView.setAdapter(photosModel.getAdapter());
        recyclerView.setLayoutManager(new LinearLayoutManager(getContext(), LinearLayoutManager.VERTICAL, false));
        recyclerView.setHasFixedSize(true);
        recyclerView.addOnScrollListener(onScrollListener);
    }

    private void initLoadingView() {
        this.progressView = (CircularProgressView) findViewById(R.id.container_loading_view_large_progressView);

        this.feedbackContainer = (RelativeLayout) findViewById(R.id.container_loading_view_large_feedbackContainer);
        feedbackContainer.setVisibility(GONE);

        ImageView feedbackImg = (ImageView) findViewById(R.id.container_loading_view_large_feedbackImg);
        Glide.with(getContext())
                .load(R.drawable.feedback_load_failed)
                .dontAnimate()
                .into(feedbackImg);

        this.feedbackText = (TextView) findViewById(R.id.container_loading_view_large_feedbackTxt);

        Button retryButton = (Button) findViewById(R.id.container_loading_view_large_feedbackBtn);
        retryButton.setOnClickListener(this);
    }

    /**
     * <br> model.
     */

    private void initModel(Activity a, int photosType) {
        this.photosModel = new PhotosObject(a, photosType);
        this.loadModel = new LoadObject(LoadObject.LOADING_STATE);
        this.scrollModel = new ScrollObject();
    }

    /**
     * <br> interface.
     */

    // on click listener.
    @Override
    public void onClick(View view) {
        switch (view.getId()) {
            case R.id.container_loading_view_large_feedbackBtn:
                photosPresenter.initRefresh(getContext());
                break;
        }
    }

    // on refresh an load listener.

    @Override
    public void onRefresh() {
        photosPresenter.refreshNew(getContext(), false);
    }

    @Override
    public void onLoad() {
        photosPresenter.loadMore(getContext(), false);
    }

    // on scroll listener.

    private RecyclerView.OnScrollListener onScrollListener = new RecyclerView.OnScrollListener() {
        @Override
        public void onScrolled(RecyclerView recyclerView, int dx, int dy) {
            super.onScrolled(recyclerView, dx, dy);
            scrollPresenter.autoLoad(dy);
        }
    };

    // view.

    // photos view.

    @Override
    public void setRefreshing(boolean refreshing) {
        refreshLayout.setRefreshing(refreshing);
    }

    @Override
    public void setLoading(boolean loading) {
        refreshLayout.setLoading(loading);
    }

    @Override
    public void setPermitRefreshing(boolean permit) {
        refreshLayout.setPermitRefresh(permit);
    }

    @Override
    public void setPermitLoading(boolean permit) {
        refreshLayout.setPermitLoad(permit);
    }

    @Override
    public void initRefreshStart() {
        loadPresenter.setLoadingState();
    }

    @Override
    public void requestPhotosSuccess() {
        loadPresenter.setNormalState();
    }

    @Override
    public void requestPhotosFailed(String feedback) {
        feedbackText.setText(feedback);
        loadPresenter.setFailedState();
    }

    // pager view.

    @Override
    public void checkToRefresh() { // interface
        if (pagerPresenter.checkNeedRefresh()) {
            pagerPresenter.refreshPager();
        }
    }

    @Override
    public boolean checkNeedRefresh() {
        return photosPresenter.getAdapterItemCount() <= 0
                && !photosPresenter.isRefreshing() && !photosPresenter.isLoading();
    }

    @Override
    public boolean checkNeedBackToTop() {
        return scrollPresenter.needBackToTop();
    }

    @Override
    public void refreshPager() {
        photosPresenter.initRefresh(getContext());
    }

    @Override
    public void scrollToPageTop() { // interface.
        scrollPresenter.scrollToTop();
    }

    @Override
    public void cancelRequest() {
        photosPresenter.cancelRequest();
    }

    @Override
    public void setKey(String key) {
        photosPresenter.setOrder(key);
    }

    @Override
    public String getKey() {
        return photosModel.getPhotosOrder();
    }

    @Override
    public boolean canSwipeBack(int dir) {
        return false;
    }

    @Override
    public int getItemCount() {
        if (loadPresenter.getLoadState() != LoadObject.NORMAL_STATE) {
            return 0;
        } else {
            return photosModel.getAdapter().getRealItemCount();
        }
    }

    // load view.

    @Override
    public void animShow(View v) {
        AnimUtils.animShow(v);
    }

    @Override
    public void animHide(final View v) {
        AnimUtils.animHide(v);
    }

    @Override
    public void setLoadingState() {
        animShow(progressView);
        animHide(feedbackContainer);
    }

    @Override
    public void setFailedState() {
        animShow(feedbackContainer);
        animHide(progressView);
    }

    @Override
    public void setNormalState() {
        animShow(refreshLayout);
        animHide(progressView);
    }

    @Override
    public void resetLoadingState() {
        animShow(progressView);
        animHide(refreshLayout);
    }

    // scroll view.

    @Override
    public void scrollToTop() {
        int firstVisibleItem = ((LinearLayoutManager) recyclerView.getLayoutManager()).findFirstVisibleItemPosition();
        if (firstVisibleItem > 5) {
            recyclerView.scrollToPosition(5);
        }
        recyclerView.smoothScrollToPosition(0);

        if (!BackToTopUtils.getInstance(getContext()).isNotified()) {
            BackToTopUtils.getInstance(getContext()).showSetBackToTopSnackbar();
        }
    }

    @Override
    public void autoLoad(int dy) {
        int lastVisibleItem = ((LinearLayoutManager) recyclerView.getLayoutManager()).findLastVisibleItemPosition();
        int totalItemCount = recyclerView.getAdapter().getItemCount();
        if (photosPresenter.canLoadMore()
                && lastVisibleItem >= totalItemCount - 10 && totalItemCount > 0 && dy > 0) {
            photosPresenter.loadMore(getContext(), false);
        }
        if (!ViewCompat.canScrollVertically(recyclerView, -1)) {
            scrollPresenter.setToTop(true);
        } else {
            scrollPresenter.setToTop(false);
        }
        if (!ViewCompat.canScrollVertically(recyclerView, 1) && photosPresenter.isLoading()) {
            refreshLayout.setLoading(true);
        }
    }

    @Override
    public boolean needBackToTop() {
        return !scrollPresenter.isToTop()
                && loadPresenter.getLoadState() == LoadObject.NORMAL_STATE;
    }

    public void onDestroy(){
        adapterWrapper.destroyAds();
    }
}`

**Comment by clockbyte** [comment]
@hoanghiephui I'll try to get with your code ASAP. Meanwhile please try our sample-app (it is very simple and perfect for testing). Do you face with the same behavior there?

**Comment by hoanghiephui** [comment]
I'm building the model MVP, as you can see, my class view containing adapter, and this class inherits from FrameLayout. Do you think this is the issue that caused the error there?

I look forward to receiving an update soon.

**Comment by clockbyte** [comment]
I can't see anything unusual in your code (you told about MVP, but the same usage is demonstrated in **sample-app**). Looking through your code quickly I found that you use `adapterWrapper.getItemCount()`. Do you use any extra-calculation for loading items to your source adapter which could depend on items count? Or maybe on indices of items? I still can't reproduce it on our sample-app. To tell the truth I have no enough time to check your code at the moment :(

**Comment by hoanghiephui** [comment]
Well, I do not see anything unusual in the source code. But maybe I'll try to watch it again. Hope you get what solutions help me.

**Comment by hoanghiephui** [comment]
I've corrected the error by removing the getItemViewType in my adapter

**Comment by clockbyte** [comment]
@hoanghiephui nice!
