### ISSUE TITLE
Min SDK required 11

### ISSUE THREAD

**Issue by mourjan** [clockbyte/admobadapter#27]
After downloading your code and including in my project I found that min SDK can be set to 9
I hope that you take this into consideration,

One more thing to note, the row containing the ad should have a predefined height cause it is against admob/adsense policy to have the ad change/shift the layout on load which might cause misleading clicks.
I'm gonne work on it, and if successful, I'll submit a Pull request,

Finally, thank you for the great job

**Comment by kot331107** [comment]
Hi! 
Thanks in advance, waiting for your pull!

**Comment by kot331107** [comment]
@mourjan Could we close it now due to the closed [pull request](https://github.com/clockbyte/admobadapter/pull/28) ?

**Comment by mourjan** [comment]
@kot331107 don't know how the chat works, but sure you can go ahead and close it.. cheers
