### ISSUE TITLE
Native express

### ISSUE THREAD

**Issue by shevkorn** [clockbyte/admobadapter#3]
hello, is there any way to add a native express inside the adapterwrapper?
thank you in advance
btw your code works great
thank you

**Comment by clockbyte** [comment]
Thanks a lot. Just trying to make your day easier:) Yeah, hardly working on that. Hope I'll update something in a few days.

**Comment by clockbyte** [comment]
Kindly check the latest commit. I'll try to add some docs ASAP but it's very similar to the Advanced ads so you could get with it yourself :)
