### ISSUE TITLE
2 ads causes lagging in my listview

### ISSUE THREAD

**Issue by ndy1g14** [clockbyte/admobadapter#33]
Anyone with the same issue? With 1 it's ok.

**Comment by kot331107** [comment]
Hi, what version do you use? Have you changed something inside Admobadapter? Also please share a code of your Activity/Fragment where you setup list and adapterwrapper

KR

**Comment by ndy1g14** [comment]
I followed the exact instructions given. I am using it with a custom EventAdapter that I made. Nothing is changed inside Admobadapter. My listView has a footerView. I load the elements dynamically with the viewHolder pattern. Everything is located inside swipeRefreshLayout. I think this is all the relevant information I got.

targetSdkVersion 24

compile 'com.github.clockbyte:admobadapter:1.2'

`events_data = new ArrayList<>();

        adapter = new EventAdapter(getActivity(),
                R.layout.listview_row, events_data, false);

        //ad adapter
        String[] testDevicesIds = new String[]{getString(R.string.testDeviceID), AdRequest.DEVICE_ID_EMULATOR};

        adapterWrapper = new AdmobExpressAdapterWrapper(getActivity(), testDevicesIds);

        adapterWrapper.setAdapter(adapter);
        adapterWrapper.setLimitOfAds(1);
        adapterWrapper.setNoOfDataBetweenAds(8);
        adapterWrapper.setFirstAdIndex(3);

        listView.setAdapter(adapterWrapper);
        //listView.setAdapter(adapter);
        //setListAdapter(adapter);
        listView.setFastScrollEnabled(false);`

**Comment by kot331107** [comment]
@ndy1g14 thx for clarification, it looks good. Let me try it with SwipeRefreshLayout. Also you could clone the latest AdmobAdapter source from **master** and try your listview with it.

**Comment by wax911** [comment]
@kot331107 I'm having the same problem as well, I've got a recyclerview on average with about 144 custom cardview with some text and images in them. Followed the tutorial on the website and all and with just 4 adviews set the application starts lagging, when I look at my logcat I can see that there is a lot of repositioning going on. Another issue which i'm having is the adviews I'm getting don't look like the ones I've set up, wierdest thing is even if I remove `MobileAds.initialize(getApplicationContext(), getString(R.string.ad_native_id));` the same adverts still get displayed. I'm guessing this happens because the library has a built in ad id it uses by default, might you any suggestion on what I should do about this?

`RecyclerView.Adapter mAdapter = new SeriesAdapter(response.body(), this);
        adapterWrapper = new AdmobRecyclerAdapterWrapper(getApplicationContext(),new String[]{AdRequest.DEVICE_ID_EMULATOR});
        adapterWrapper.setAdapter(mAdapter);
        adapterWrapper.setLimitOfAds(4);
        adapterWrapper.setNoOfDataBetweenAds(10);
        adapterWrapper.setFirstAdIndex(2);
        recyclerView.setAdapter(adapterWrapper);`

**Comment by kot331107** [comment]
@wax911 1. please try our sample app on your test device (switch a main activity to .express.MainActivity_RecyclerView_Express in the manifest) and try with the same parameters as in your app (150 items for source collection and so on). Is it freeze too?
2. I have the very same app and its OK for me (no freeze, no much repositioning). So please provide here the code where you filling/updating your **source** adapter with cardviews. 
3. sure, the library has it's default test unit id. Please use a different constructor to inject your own unit id which you could get from Admob Console. 
**NOTE** that `MobileAds.initialize(...)` expects the **Application Id** (not the unit id of the native banner!) from **your Admob Console**. And it does not have any influence on the ad content! This string makes to init Admob/Firebase things as early as possible.

**Comment by kot331107** [comment]
@wax911 Friendly reminder. Have you got the stuff about the correct unit ids?  Have you tried our sampleapp to check freezes?

**Comment by wax911** [comment]
@kot331107 Oh man, sorry for the late reply. I just noticed that there was another optional constructor on the `AdmobRecyclerAdapterWrapper(...)` method, everything seems fine now. Thanks for pointing out the previous reminders 👍

**Comment by kot331107** [comment]
@ndy1g14 How you doing? I have investigated the issue and I have no freeze with the latest version. I'm going to release next v1.3 very soon so please watch for news :)
