### ISSUE TITLE
No ads in production

### ISSUE THREAD

**Issue by ohadmata** [clockbyte/admobadapter#36]
Hello.
I installed the admobadapter.
Its work great with test device ID

but in production ads not visible :-(

any Ideas?

* I tried to change the banner id - no results
* The catlog is empty (No admob/admobadapter mention)
* I tried to remove my costume layout - no results
* Interesting info - the firebase console shows some ad views

Constructor:
```
        //debug mode
        //String[] testDevicesIds = new String[]{"E7AC2F56BC1BF35EEC5C63E981C438A8", AdRequest.DEVICE_ID_EMULATOR};
        //adapterWrapper = new AdmobRecyclerAdapterWrapper(getContext(),testDevicesIds);

        //release mode
        adapterWrapper = new AdmobRecyclerAdapterWrapper(getContext(),getResources().getString(R.string.banner_ad_unit_id));
```

Code:
```
        adapterWrapper.setAdapter(mAdapter);
        adapterWrapper.setLimitOfAds(50);
        adapterWrapper.setNoOfDataBetweenAds(Integer.parseInt(getResources().getString(R.string.ad_rate)));
        adapterWrapper.setFirstAdIndex(Integer.parseInt(getResources().getString(R.string.ad_rate)));

        InstallAppAdLayoutContext installContext  = new InstallAppAdLayoutContext(R.layout.ad_app_install);
        adapterWrapper.setInstallAdsLayoutContext(installContext);
        ContentAdLayoutContext contentContext  = new ContentAdLayoutContext (R.layout.ad_content);
        adapterWrapper.setContentAdsLayoutContext(contentContext);

        mRecyclerView.setAdapter(adapterWrapper);
```

**Comment by udayathreya** [comment]
Use expressadsadapter

**Comment by ohadmata** [comment]
But I want to change the default layout.

**Comment by udayathreya** [comment]
Native Ads Advanced is currently in a closed beta with a limited group of
publishers, but you're welcome to take a look through ourNative
<https://firebase.google.com/docs/admob/android/native-advanced> Ads
Advanced <https://firebase.google.com/docs/admob/android/native-advanced>
guide.
From admob dev

**Comment by ohadmata** [comment]
Thanks.
There is any way to wrap the Express ads with container?
I just want to wrap the ads with card view.

**Comment by udayathreya** [comment]
In your adapter layout include adview, hide or show when you want just like
any normal view

**Comment by ohadmata** [comment]
But I want the admobadapter will manage the ads.

There is any way to wrap the Admobadapter ad layout ?
In the worst case I will edit the source code of the project and compile it again.

**Comment by kot331107** [comment]
@ohadmata try to search in logcat filtering by "Ads". Does it show something like incorrect size or not enough place to show Ad?

**Comment by ohadmata** [comment]
> Nope

**Comment by ohadmata** [comment]
I changed the adview to express.
built new release version with signed apk.
When I tested the app in another phone (Not the developer phone)
its wrote (LOGCAT)

> Use AdRequest.Builder.addTestDevice("CE199CE798613391BAFE54340255C5ED") to get test ads on this device


this is the production apk from the android play store
any ideas?

thanks

**Comment by kot331107** [comment]
@ohadmata Sorry I got you wrong. @udayathreya is absolutely right on Advanced Native Ads (**AdmobRecyclerAdapterWrapper**), it's still in beta release. So please use Express ads instead (as a temp solution maybe), it already works quite stable. 
Googling on your problem I found the following https://groups.google.com/forum/#!topic/google-admob-ads-sdk/yCiMLY3eqNE
Looks like you simply have to wait for a while to get it work :)

**Comment by ohadmata** [comment]
I will wait.
thanks!

**Comment by kot331107** [comment]
@ohadmata 

> There is any way to wrap the Admobadapter ad layout ?

Due to our dear contributors we're going to release v1.3 very soon and there you could find a feature to wrap each ad block into your custom ViewGroup
