### ISSUE TITLE
GridLayoutManger support for RecyclerView?

### ISSUE THREAD

**Issue by vipulasri** [clockbyte/admobadapter#37]
I tried implementing the sample code and changed the `Linear Layout Manager` provided to `Recycycler View` to `Grid Layout Manager` then the code doesn't work fine as Ads doesn't gets loaded.

**Comment by kot331107** [comment]
Hi,

We are not going to support GridLayout soon. You are very welcome to provide a pull request and help our library if you'll succeed.
