### ISSUE TITLE
If ads fail to load RecyclerViewAdapter hides data

### ISSUE THREAD

**Issue by lujop** [clockbyte/admobadapter#38]
I discovered that in my application where custom data appears but after the add failed to load (Due to error 0) then my data is removed.

It can be easily reproduced in sample application, just enter an invalid ad id in MainActivity_RecyclerView_Express and no data appears.

**Comment by kot331107** [comment]
Thx, we'll check it!

**Comment by kot331107** [comment]
@lujop fixed. Will be released to maven **v1.3**
