### ISSUE TITLE
First position of ads

### ISSUE THREAD

**Issue by IHNEL** [clockbyte/admobadapter#4]
It should be great if I can set the index of first ads item on the list (I use recyclerview). At this time, the first ads index always equals to `mNoOfDataBetweenAds`

**Comment by clockbyte** [comment]
@IHNEL I'm gonna implement it shortly...

**Comment by clockbyte** [comment]
@IHNEL Hi, kindly pull the first_adv_index branch (experimental) to get this feature.

**Comment by IHNEL** [comment]
Thanks.
