### ISSUE TITLE
It is not working with RealmRecyclerView Adapter

### ISSUE THREAD

**Issue by Shajeel-Afzal** [clockbyte/admobadapter#41]
Hi, 

I am trying to use it with RealmRecyclerView Adapter (https://github.com/realm/realm-android-adapters) but it is not showing any content. Without `AdmobExpressRecyclerAdapterWrapper`, it is working perfectly. 

I have followed the instructions that are mentioned at https://github.com/clockbyte/admobadapter/wiki/Cookbook#the-recipe-3-for-a-recyclerview-scrolling-with-express-ads

Also, App crashes whey i destroy the Adapter in the onDestroy method with the following exception:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Looper android.content.Context.getMainLooper()' on a null object reference
       at com.clockbyte.admobadapter.AdmobFetcherBase.notifyObserversOfAdSizeChange(AdmobFetcherBase.java:126)
       at com.clockbyte.admobadapter.AdmobFetcherBase.destroyAllAds(AdmobFetcherBase.java:118)
       at com.clockbyte.admobadapter.expressads.AdmobFetcherExpress.destroyAllAds(AdmobFetcherExpress.java:145)
       at com.clockbyte.admobadapter.expressads.AdmobExpressRecyclerAdapterWrapper.destroyAds(AdmobExpressRecyclerAdapterWrapper.java:311)
```

Library version:`compile 'com.github.clockbyte:admobadapter:1.2'`
OS Version 6.0

Any suggestions?

**Comment by kot331107** [comment]
@Shajeel-Afzal Hi,

Crash was fixed, will be available in upcoming **v1.3.**. Actually we don't support any thirdparties. However We'll check what's going on with RealmRecyclerView...a bit later OK?

**Comment by Shajeel-Afzal** [comment]
Thanks @kot331107!

**Comment by kot331107** [comment]
@Shajeel-Afzal There was another issue https://github.com/clockbyte/admobadapter/issues/62 and he said that he was able to integrate with Realm adapter. Could you please ask the issuestarter?
