### ISSUE TITLE
Medium and Small Admob Adds are not shown

### ISSUE THREAD

**Issue by Geodark** [clockbyte/admobadapter#43]
Hi,

I was able to integrate your library on a project that uses . I successfully added Large Admob Adds but for Small and Medium Native Admob Express ads I was unable. 
I am using `AdmobRecyclerAdapterWrapper` in my app and this is the error that I receive:

```
E/Ads: Malformed native JSON response.
org.json.JSONException: Index 0 out of range [0..0)
  at org.json.JSONArray.get(JSONArray.java:282)
  at org.json.JSONArray.getJSONObject(JSONArray.java:510)
  at com.google.android.gms.ads.internal.renderer.nativeads.h.a(:com.google.android.gms.DynamiteModulesA:238)
  at com.google.android.gms.ads.internal.webview.c.a(:com.google.android.gms.DynamiteModulesA:955)
  at com.google.android.gms.ads.internal.webview.u.run(:com.google.android.gms.DynamiteModulesA:44)
  at android.os.Handler.handleCallback(Handler.java:733)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:136)
  at android.app.ActivityThread.main(ActivityThread.java:5017)
  at java.lang.reflect.Method.invokeNative(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:515)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
  at dalvik.system.NativeStart.main(Native Method)

```
I tried with `AdmobExpressRecyclerAdapterWrapper `also but when I am using this to set the AdSize in `ExpressAdPreset`, I receive the warning:

`W/Ads: Not enough space to show ad`

I think this is a padding issue but I don't know how I can set the padding on the adView from your adapter

Is this a known issue for you?

**Comment by kot331107** [comment]
@Geodark Hi,

Please correct me if I'm wrong but the Advanced Native ads are still in Beta. So you should definitely use the  **AdmobExpressRecyclerAdapterWrapper**. 
On the issue "W/Ads: Not enough space to show ad": I had the same, it is closely connected with paddings/margins and I'm not sure but maybe it's a kind of bug in Express ads...
However I solved it after I removed all the paddings from the RecyclerView itself and from all parent Views.  Then I set a required paddings/margins for all items' views but ads. The gist is to let ads fill the full width of a screen.

**Comment by Geodark** [comment]
Hi @kot331107,

Thanks a lot for your reply.
You are right: the Native Advance Ads are in beta, but I didn't know that `AdmobRecyclerAdapterWrapper  `is for advanced ads. Although the large were shown when I used this and without the padding - I think ths wrapper does this for us.
I will try to use  `AdmobExpressRecyclerAdapterWrapper`. There is a chance to have a **gist** with the removed paddings for RecyclerView as you suggested?

**Comment by kot331107** [comment]
@Geodark hi,

I guess you don't need a **gist**! You should simply remove all paddings/margins in the app from RecyclerView and its'parents.

**Comment by kot331107** [comment]
@Geodark how's it going? Just a friendly reminder...have you handled it successfully?

**Comment by Geodark** [comment]
@kot331107 Hi,

I was managed to user Express Wrapper and to remove the paddings from RecyclerView in case of Native ads, but now the Large native ads are not shown if I use in Wrapper constructor only the Ad Unit Id.

I've managed to show the large ad when I used ExpressAdPreset - but in this case the height of the ad it's hard coded.
Do you know something about it?

**Comment by Geodark** [comment]
@kot331107 hi again,

In addition to this issue. In my app I want to start different activities in ListPostItemTouchListener listener - we I click the coresponding item from the list. I determine the view type and I wanted to see if it's express ads but the following function it's private. It's possible to make this function public in the next release:

**AdmobExpressRecyclerAdapterWrapper.java:130 (version 1.3.0 of this library)**
```
    private int getViewTypeAdExpress(){
        return getViewTypeBiggestSource() + VIEW_TYPE_AD_EXPRESS + 1;
    }
```

**Comment by kot331107** [comment]
@Geodark hi,

Sure it's not hard to make it public...but let's get with it together. Am I right that you want to do some certain action (start any specific activity) on touch on the corresponding item ? And you need some way to determine what the exact item was clicked outside of the wrapper, let's say right in your listener? Then [see this post](https://github.com/clockbyte/admobadapter/wiki/Cookbook#in-case-you-stucked-with-getting-the-correct-itemindex-of-a-source-collection-in-a-listviewrecyclerview-click-handler).

On the ad's height: When you created ad banner in the Admob Console you'd set there a size for it with exact widthxheight. So you should pass this height to the to the ExpressAdPreset#AdSize like it [was shown here](https://github.com/clockbyte/admobadapter/wiki/Cookbook#in-case-you-want-to-use-a-multiple-unit-ids). Try to leave the width as FULL_WIDTH and set the height from your banner's options .
