### ISSUE TITLE
Listview blank when ads failing to load

### ISSUE THREAD

**Issue by xbroak** [clockbyte/admobadapter#44]
There was a problem getting an ad response. ErrorCode: 0
W/Ads: Failed to load ad: 0

Which is fine, but suddenly it makes my list go blank after loading:

       String[] testDevicesIds = new String[]{getString(R.string.testDeviceID), AdRequest.DEVICE_ID_EMULATOR};
        adapterWrapper = new AdmobExpressAdapterWrapper(getActivity(), testDevicesIds);
        adapterWrapper.setAdapter(adapter);
        adapterWrapper.setLimitOfAds(3);
        adapterWrapper.setNoOfDataBetweenAds(10);
        adapterWrapper.setFirstAdIndex(2);

**Comment by kot331107** [comment]
@xbroak Hi,

Do you fill your adapter with items after these strings? Could you reproduce it on our **sampleapp**? If negative then could you provide a code of your adapter (which you inject to the wrapper)?

**Comment by kot331107** [comment]
@xbroak Hi,

Are you able to reproduce it in our **sampleapp** or in your app only? Do you fill your adapter with items after these strings? Could you please provide the code of your adapter (not wrapper one)?

**Comment by kot331107** [comment]
@xbroak just to remind...Or have you solved the issue yourself?

**Comment by xbroak** [comment]
No worries, i was loading the list items for and everything was near identical to the sample. I've since decided against AdMob altogether, please don't concern yourself! :)
