### ISSUE TITLE
Supporting FirebaseRecyclerAdapter

### ISSUE THREAD

**Issue by kerolloskromer** [clockbyte/admobadapter#48]
i`ve implemented a way to support FirebaseRecyclerAdapter , how to share it with you ?

**Comment by kot331107** [comment]
@kerolloskromer Hi, thanks for your participation!
Kindly fork the latest **experimental** branch then do your changes in your fork in a way you prefer. Then do a pull request back to our **experimental** branch. I'll check it then and commit.

KR

**Comment by kerolloskromer** [comment]
Hi , Thanks for your response , actually my implementation is at the user side , i configured  the FirebaseRecyclerAdapter so it can be wrapped with your liberary , so all the user have to do is to use my configured adapter.

You can find it here:
https://www.dropbox.com/sh/uqjftoph679u064/AADRzfhAJPoFqC9jMSowSIc5a?dl=0

I hope it`s useful and i hope i didn`t waste your time

Thank you

**Comment by kot331107** [comment]
I see, you good! :+1: 
let me check your code a bit later, please don't remove your code from dropbox, OK?

**Comment by kerolloskromer** [comment]
sure , thanks

**Comment by kot331107** [comment]
@kerolloskromer I've just looked through, 

It's an adapter for your source data, am I right? So I guess it would be nice if you'll share it in your repo in Github and give me a link then I could share with people who'll ask about the FirebaseAdapter interaction (I remember at least one issue with this question). And thanks again man!

KR

**Comment by kerolloskromer** [comment]
https://github.com/kerolloskromer/database

**Comment by kot331107** [comment]
@kerolloskromer No no, that's OK!

**Comment by kerolloskromer** [comment]
Thank you
