### ISSUE TITLE
Changing the adsize and showing different ads in listview.

### ISSUE THREAD

**Issue by vivekkarn** [clockbyte/admobadapter#52]
I am using this library for adding adding **Native Ads Express** to _listview_ via an adapter to my app [.](https://play.google.com/store/apps/details?id=com.vivek.pocketmedbook) I'm extremely thankful for making this job easier to newbies but I need some help. I'm unable to change the **AdSize** as well as all the ads in the listview are same. Isn't it possible to show **different ads in same listview**?
`mPointList = mDBHelper.getListPoints(table);
adapter = new ListPointAdapter(this, mPointList);
String[] testDevicesIds = new String[]{getString(R.string.testDeviceID), AdRequest.DEVICE_ID_EMULATOR};
adapterWrapper = new AdmobAdapterWrapper(this, testDevicesIds);
adapterWrapper.setAdapter(adapter);
adapterWrapper.setLimitOfAds(8);
adapterWrapper.setNoOfDataBetweenAds(30);
adapterWrapper.setFirstAdIndex(10);
listDetail.setAdapter(adapterWrapper);`
 Please help.

**Comment by kot331107** [comment]
@vivekkarn Hi!

I guess it is the thing you are looking for https://github.com/clockbyte/admobadapter/wiki/Cookbook#in-case-you-want-to-use-a-multiple-unit-ids

**Comment by vivekkarn** [comment]
Pardon me, but that example is for recyclerview not listview.

**Comment by kot331107** [comment]
@vivekkarn the same should work for **AdmobExpressAdapterWrapper**
