### ISSUE TITLE
Items not showing when internet is not connected

### ISSUE THREAD

**Issue by gssinghgautam** [clockbyte/admobadapter#53]
items in recyclerview not showing when internet is on or availabe, its working fine when internet is available

**Comment by gssinghgautam** [comment]
can you please help me regarding this

**Comment by sunilsunny565** [comment]
I am also having this issue .Any update on this . ?

**Comment by sunilsunny565** [comment]
For me the issue was inside AdmobFetcherExpress if the add is failed to load then the parent view visibilty was set as gone. like this
```
 if(adViewEx.getAdView().getParent()!=null)
            ((View) adViewEx.getAdView().getParent()).setVisibility(View.GONE); 
```

I have changed this to this
       
      ```
  if(adViewEx.getAdView() !=null)
             adViewEx.getAdView().setVisibility(View.GONE); 
```

So that only the adview visibily is gone.

**Comment by diabloo** [comment]
same issue , any solution for this ?

**Comment by sunilsunny565** [comment]
@diabloo Did you tried my workaround ?. Or  you can add the adView to a Realative or LineraLayout so that only it's parent's visibility will be gone.

**Comment by kot331107** [comment]
Guys, I'll check it today.

**Comment by diabloo** [comment]
@sunilsunny565 i tried it but the application crash 
`
    java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes.
`

**Comment by sunilsunny565** [comment]
@kot331107  Thanks it's working in the latest build.Only one issue an empty view will be there as long as the ad fails. I tried something like this in AdmobExpressAdapterWrapper to get rid of the problem . 
```
   @Override
    public View getView(int position, View convertView, ViewGroup parent) {
      if(getItemViewType(position) == getViewTypeAdExpress() && isNetworkAvailable)
        {
         // rest of code
        return wrapper;
        }else{
          //rest of code
        return mAdapter.getView(origPos, convertView, parent);
       }
  }
```

That is make a network check on getView ,but in this case I am getting duplicate view of listItem on ad position for sometime and then it disappears.Is there a way to get rid off that empty cell ?.
