### ISSUE TITLE
Issue using this with custom RecyclerView adapter

### ISSUE THREAD

**Issue by IamJackppot** [clockbyte/admobadapter#55]
I am trying to use this with a custom RecyclerView adapter and a syntax error comes up using set adapter with my custom RecyclerView Adapter.

It's because I am using a nested view holder within my adapter, not the standard `RecyclerView.ViewHolder`.

How can I use this when using a custom view holder?

**Comment by kot331107** [comment]
@IamJackppot Hi, 
Does your VH extend `RecyclerView.ViewHolder`? So kindly see the following issues
https://github.com/clockbyte/admobadapter/issues/18
https://github.com/clockbyte/admobadapter/issues/46

KR
