### ISSUE TITLE
Please support Realm adapter

### ISSUE THREAD

**Issue by mouness2020** [clockbyte/admobadapter#62]
Hello,
Please support Realm adapter

Regards,,

**Comment by mouness2020** [comment]
Ok i followed this explain 
[https://github.com/clockbyte/admobadapter/wiki/Cookbook#the-recipe-3-for-a-recyclerview-scrolling-with-express-ads]
just casted RealmRecyclerViewAdapter by `(RecyclerView.Adapter)recyclerViewAdapter`
and everything works fine
thanks,,,

**Comment by kot331107** [comment]
@mouness2020  Ok, welcome
