### ISSUE TITLE
QUESTION : Layout Height Not Changing!! 

### ISSUE THREAD

**Issue by peter1408** [clockbyte/admobadapter#67]
i have successful implement this project , and it work like a charm , smooth .. really ! 
but i have some trouble with the layout it is using ! i wanted to use my own layout , i have read your cookbook for the same , but didnt got how to do it ! i mean is it possible with your code ! if i keep it offline as project library in my code , and change some layout or something ! is tht possible ?

**Comment by peter1408** [comment]
and also i have read that Native Ads Advanced  are still under Beta !

**Comment by peter1408** [comment]
and one more thing  , how to change the test id's to the live id's (unit id and app id ), is it that i have to just replace the test id with my live id in string file or i have to do more of something

**Comment by kot331107** [comment]
@peter1408 Hi,
you are able to customize the ad appearance only for Advanced Native ads (and it is in Beta now so we don't fully support it at the moment). 
As for Express ads, you definitely can customize it. But it could be done only from your Admob console (create there one native express banner and you will get it, it is really simple).
On live/test UnitIds: yeah you are mostly right. Here is some snippet for you which handles both cases (see the condition on flag IsDebug):

```java
    //testDevicesId - is simply an resource string array of my devices ids which I use for testing
    ArrayList<String> testDevices = new ArrayList<>(Arrays.asList(testDevicesId));
    //add emulator to the list of test devices
    testDevices.add(AdRequest.DEVICE_ID_EMULATOR);
    //IsDebug is the global boolean which means if we are in release mode or not.
    if(IsDebug) {
        //if debug I use an appropriate ctor. then AdmobExpressRecyclerAdapterWrapper 
        //uses pre-defined adUnitId for testing (which is correct due to the Admob 
        //development docs). The 1st param is a context so since you use Fragment, 
        //pass getActivity(). 3rd parameter is a copy of test ids array
        FeedAdapterWrapper = new AdmobExpressRecyclerAdapterWrapper(getActivity(), null, testDevices.toArray(new String[0])){
        //you could miss this override if you wish. It's for wrapping the ad block into your custom view
        @Override
        protected ViewGroup wrapAdView(NativeExpressAdViewHolder adViewHolder, ViewGroup parent, int viewType) {
            return MessagesFragment.this.wrapAdView(adViewHolder, parent);
        }
    };
    } 
    //if release I use the same ctor but instead of null 
    //I pass my unitId from Admob console (as banner_admob_unit_id:String). Then 
    //AdmobExpressRecyclerAdapterWrapper uses my unitId  for Release
    else FeedAdapterWrapper = new AdmobExpressRecyclerAdapterWrapper(getActivity(), banner_admob_unit_id, testDevices.toArray(new String[0])){
        //you could miss this override if you wish.
        @Override
         protected ViewGroup wrapAdView(NativeExpressAdViewHolder adViewHolder, ViewGroup parent, int viewType) {
             return MessagesFragment.this.wrapAdView(adViewHolder, parent);
         }
    };

    //set your adapter and other params to the wrapper
    FeedAdapterWrapper.setAdapter(FeedAdapter);
    FeedAdapterWrapper.setNoOfDataBetweenAds(10);
    FeedAdapterWrapper.setLimitOfAds(0);
    FeedAdapterWrapper.setFirstAdIndex(0);
    //set your wrapper as an adapter for your list
    rvMessages.setAdapter(FeedAdapterWrapper);
```

**Comment by peter1408** [comment]
i understood! A big hug for you ... Saved a lot of overhead !

**Comment by peter1408** [comment]
i have customised my native ad from the console , have replaced the ids to production unit ids . 
All working good . 

Just one more query . i am having trouble with the white space which come early , i understand the guidelines provide \: as you already said :  "it's against Admob policies to show ad block suddenly by expanding it from between the items because user can click on it randomly. So we need to show the place where the ad will be presented "

but can i put the white space in a card view something ?? 
its just a white patch on my screen , i tried to replace the "Ad Loading textView" with my progress bar but its wrapped . can you guide me through this small tweak more ?

**Comment by peter1408** [comment]
okay i have add the ad the card view , all good , thanx for your cook book support , 

All just now i want is the height problem 
https://dl2.pushbulletusercontent.com/G51rAtGJn4Aa9WXyjsq6NiP91gQ1ooVa/screenshot.jpg

i need to wrap the height of the Ad , i have tried using the AdSize class too , but nothing happens it matches the height of the white space
Please read the above comment too

**Comment by kot331107** [comment]
@peter1408 Hi again, 
if I understand your question correctly, then No, you can't change this height (bounded by arrows on your screenshot). This white space is the ad view itself and you can't change it's internal margins, sizes somehow but only via tools in your Admob Console. 
Also you could wrap it in a **CardView** as it was shown in my snippet above and in the Cookbook...And take into account that it against Admob rules to decrease the ad block's height (at least because usually ad publishers pay money to show it exactly in the way they want through your app :) )

**Comment by peter1408** [comment]
but this is the smallest native layout am using 

https://dl2.pushbulletusercontent.com/M8zk0dJE4tzRkgSwu18CPeFBCfACoGBU/screenshot%20%281%29.jpg

**Comment by kot331107** [comment]
@peter1408 so have you tried to set **adapterWrapper.setAdSize(new AdSize(AdSize.FULL_WIDTH,100));** ?

**Comment by peter1408** [comment]
this method is not their in the adapterWrapper in 1.3.2 V

**Comment by kot331107** [comment]
@peter1408 Just to clarify, have you seen this `adapterWrapper.setAdSize(new AdSize(AdSize.FULL_WIDTH,150));` code somewhere in the Cookbook?

**Comment by peter1408** [comment]
Yes i have seen but its not applicable !

**Comment by kot331107** [comment]
@peter1408 Could you please provide me a link?

**Comment by peter1408** [comment]
i dnt know the exact link but have read in some of the closed issues in this library 

https://github.com/clockbyte/admobadapter/issues/18 (The comment added by Ghost)

**Comment by kot331107** [comment]
What you mean "their" exactly? :) Let me check it and I'll return back to you.

**Comment by peter1408** [comment]
i mean the admobadapter class .

**Comment by kot331107** [comment]
oh, it's mine btw :)

**Comment by peter1408** [comment]
ha-ha-ha... hahaha!! :) it is yours !

**Comment by kot331107** [comment]
@peter1408 Plz check if it helped?

**Comment by peter1408** [comment]
no no ! am using Listview ! this ctor is for recycleview

**Comment by kot331107** [comment]
@peter1408  why you say that? o_O `public AdmobExpressAdapterWrapper(Context context, String admobReleaseUnitId, AdSize adSize)` this ctor is definitely for ListView :D

**Comment by peter1408** [comment]
but that is not working . it still taking the complete size ! what shall i do ?

**Comment by peter1408** [comment]
can you tell me where have you set the height of the view which is been added before the ad are shown ??

**Comment by peter1408** [comment]
am sorry but i offline downloaded your library , and sawed that in your ExpressAdPreset class 

private static final AdSize SIZE_DEFAULT_EXPRESS = new AdSize(AdSize.FULL_WIDTH, 100);

is set only one time and using the ctor for listview / or as to be specific 
public AdmobExpressAdapterWrapper(Context context, String admobReleaseUnitId, AdSize adSize)

this line dont work to change the height . i dont know , i edited ExpressAdPreset  to set my css file height . and it woked their . 

sorry if am getting too deep . or if am wrong ! i got my work done ! thank anyways for this beautiful code work of your .. appreciate it really
