### ISSUE TITLE
ads are not showing

### ISSUE THREAD

**Issue by sid9890** [clockbyte/admobadapter#68]
@kot331107 hi,
W/Ads: Timed out waiting for ad response.
I/Ads: Scheduling ad refresh 60000 milliseconds from now.
W/Ads: Failed to load ad: 2

this is my LogCat showing.

**Comment by kot331107** [comment]
@sid9890  Okay, `W/Ads: Failed to load ad: 2` from the docs https://developers.google.com/android/reference/com/google/android/gms/ads/AdRequest#ERROR_CODE_INVALID_REQUEST means you have a bad/slow internet connection 
**OR** you have something that blocks the ad loading. Do you use any [Adblocker](http://stackoverflow.com/questions/21269998/admob-isnt-working-because-of-i-think-google-play-services) on your device? Could you try via a different device (an emulator should work also)? If you experience issue on the emulator then you'd try on the real device...

**Comment by sid9890** [comment]
@kot331107 
i tried on real device same problem
i am not using any ad blocker

**Comment by sid9890** [comment]
@kot331107  hi,
 another problem,
it was running fine just now in my testing mode.
but as soon as i jumped on release mode, i made this chnge-
 adapterWrapper = new AdmobExpressAdapterWrapper(this,getString(R.string.test_admob_app_id))

 it showing this error

04-21 16:09:33.195 24658-24658/com.example.admin.listviewnativeads I/com.clockbyte.admobadapter.expressads.AdmobFetcherExpress: onAdFailedToLoad 0
04-21 16:09:33.265 24658-24658/com.example.admin.listviewnativeads I/com.clockbyte.admobadapter.expressads.AdmobFetcherExpress: Fetching Ad now
04-21 16:09:33.275 24658-24658/com.example.admin.listviewnativeads D/DynamitePackage: Instantiating com.google.android.gms.ads.ChimeraAdManagerCreatorImpl
04-21 16:09:33.275 24658-24658/com.example.admin.listviewnativeads I/Ads: Starting ad request.
04-21 16:09:33.325 1019-1032/? D/AudioService: getStreamVolume 3 index 150
04-21 16:09:33.335 1019-4124/? D/AudioService: getStreamVolume 2 index 150
04-21 16:09:33.355 1019-1413/? D/ActivityManager: startService callerProcessName:com.google.android.gms, calleePkgName: com.google.android.gms
04-21 16:09:33.365 1019-1481/? D/ActivityManager: startService callerProcessName:com.google.android.gms, calleePkgName: com.google.android.gms
04-21 16:09:33.395 1019-1032/? D/ConnectivityService: returning getNetworkInfo for network type 0 : [type: MOBILE[] - MOBILE, state: DISCONNECTED/DISCONNECTED, reason: (unspecified), extra: (none), roaming: false, failover: false, isAvailable: true, isConnectedToProvisioningNetwork: false]
04-21 16:09:33.435 1976-1870/? I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-21 16:09:33.435 1976-1870/? I/qtaguid: Tagging socket 101 with tag 3000010500000000{805306629,0} for uid -1, pid: 1976, getuid(): 10012
04-21 16:09:33.945 1976-1870/? I/qtaguid: Untagging socket 101
04-21 16:09:33.945 1976-1870/? W/Ads: Received error HTTP response code: 403
04-21 16:09:33.955 24658-1831/com.example.admin.listviewnativeads W/Ads: There was a problem getting an ad response. ErrorCode: 0
04-21 16:09:33.955 24658-24658/com.example.admin.listviewnativeads W/Ads: Failed to load ad: 0
04-21 16:09:33.955 24658-24658/com.example.admin.listviewnativeads I/com.clockbyte.admobadapter.expressads.AdmobFetcherExpress: onAdFailedToLoad 0
04-21 16:09:34.015 24658-24658/com.example.admin.listviewnativeads I/com.clockbyte.admobadapter.expressads.AdmobFetcherExpress: Fetching Ad now
04-21 16:09:34.015 24658-24658/com.example.admin.listviewnativeads D/DynamitePackage: Instantiating com.google.android.gms.ads.ChimeraAdManagerCreatorImpl
04-21 16:09:34.025 24658-24658/com.example.admin.listviewnativeads I/Ads: Starting ad request.
04-21 16:09:34.065 1019-4124/? D/AudioService: getStreamVolume 3 index 150
04-21 16:09:34.065 1019-1457/? D/AudioService: getStreamVolume 2 index 150
04-21 16:09:34.065 1019-4197/? D/ActivityManager: startService callerProcessName:com.google.android.gms, calleePkgName: com.google.android.gms
04-21 16:09:34.065 1019-1418/? D/ActivityManager: startService callerProcessName:com.google.android.gms, calleePkgName: com.google.android.gms
04-21 16:09:34.095 1019-1783/? D/ConnectivityService: returning getNetworkInfo for network type 0 : [type: MOBILE[] - MOBILE, state: DISCONNECTED/DISCONNECTED, reason: (unspecified), extra: (none), roaming: false, failover: false, isAvailable: true, isConnectedToProvisioningNetwork: false]
04-21 16:09:34.135 1976-1868/? I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-21 16:09:34.135 1976-1868/? I/qtaguid: Tagging socket 188 with tag 3000010500000000{805306629,0} for uid -1, pid: 1976, getuid(): 10012
04-21 16:09:35.155 1019-3471/? D/SSRM:n: SIOP:: AP = 410, LCD = 0
04-21 16:09:35.165 1019-3471/? D/ConnectivityService: returning getNetworkInfo for network type 1 : [type: WIFI[] - WIFI, state: CONNECTED/CONNECTED, reason: (unspecified), extra: "TP-LINK_BA13F6", roaming: false, failover: false, isAvailable: true, isConnectedToProvisioningNetwork: false]
04-21 16:09:35.445 1019-1418/? D/BatteryService: !@BatteryListener : batteryPropertiesChanged!

**Comment by sid9890** [comment]
Am i doing something wrong here????


` private void initListViewItems() {
        adapterWrapper = new AdmobExpressAdapterWrapper(this,getString(R.string.test_admob_app_id)) {
            @Override
            protected ViewGroup wrapAdView(NativeExpressAdViewHolder adViewHolder, ViewGroup parent, int viewType) {
                
                NativeExpressAdView mAdView = adViewHolder.getAdView();

                AbsListView.LayoutParams lp = new AbsListView.LayoutParams(AbsListView.LayoutParams.MATCH_PARENT,
                        AbsListView.LayoutParams.WRAP_CONTENT);
                RelativeLayout container = new RelativeLayout(MainActivity.this);
                container.setLayoutParams(lp);

                TextView textView = new TextView(MainActivity.this);
                textView.setLayoutParams(lp);
                textView.setText(" loading...");
                textView.setTextColor(Color.RED);
        
                container.addView(textView);
                //wrapping
                container.addView(mAdView);
                //return wrapper view
                return container;
            }
        };
        adapterWrapper.setAdapter(adapter); 
        adapterWrapper.setLimitOfAds(10);
        adapterWrapper.setNoOfDataBetweenAds(10);
        adapterWrapper.setFirstAdIndex(2);
        lvMessages.setAdapter(adapterWrapper); `

**Comment by kot331107** [comment]
@sid9890 Congrats buddy! Your code looks good for me. I guess the problem is something like [this one](http://stackoverflow.com/questions/38378002/admob-ads-not-loading-failed-to-load-ad-0). Have you created your live(release) Admob Unit Id recently? So you have to wait a bit while your Unit Id would be processed onthe Admob side.

**Comment by sid9890** [comment]
@kot331107  hi,
thanks buddy!!
my account is created last week and i am using old AdUnitId.
Even though i will wait.if any problem occures i will contact you,thanks in advance!!!

**Comment by kot331107** [comment]
@sid9890 okay...it's strange, because usually a day is totally enough...have you used the 
` MobileAds.initialize(getApplicationContext(), getString(R.string.test_admob_app_id));`
somewhere on startup of your app (for example in **MainActivity.onCreate()**)? It's not necessary AFAIK but a kind of recommended option. test_admob_app_id - is an appId from your AdmobConsole (it DIFFERS from your Unit Id!!!). 
And does it work with test UnitId (just pass unitId to the constructor of a wrapper as **null**)?
