### ISSUE TITLE
Hide Ad Position till Ads Getting Loaded

### ISSUE THREAD

**Issue by karopass** [clockbyte/admobadapter#7]
Hi ! I am wondering if there possibility with recycler view like view.GONE and view.VISIBLE on ads loaded, loading as well loading failed.

**Comment by clockbyte** [comment]
@karopass Hi,
I really tried to implement it but I had no enough time to get with it. Maybe a bit later! It's really annoying. If you'll solve it earlier than me, kindly suggest a commit to the trunk.

**Comment by clockbyte** [comment]
@karopass Please get the latest from the branch https://github.com/clockbyte/admobadapter/tree/experimental. I have fixed this issue there. I should warn you that I've made a lot changes there and you could get some errors after updating but I'm sure that this game is worth the candle :) Also I'm going to make my library Gradle/Maven-linkable soon...
