### ISSUE TITLE
Ad is loading - red line getting displayed in ad

### ISSUE THREAD

**Issue by Sahana312** [clockbyte/admobadapter#74]
I have implemented Express ads in my listview and recycler view. But I am getting a red colored line on the Ad. It is displayed when the Ad is loading... text comes. How do we eliminate this line and the ad is loading text?

**Comment by kot331107** [comment]
@Sahana312  please see https://github.com/clockbyte/admobadapter/wiki/Cookbook#the-recipe-3-for-a-recyclerview-scrolling-with-express-ads
