### ISSUE TITLE
3 times refreshing my listview

### ISSUE THREAD

**Issue by sid9890** [clockbyte/admobadapter#75]
i am using listview native ad sample in my app,its working fine but first time my list items are showing,den 2 times very fast get invisible my listview and again its visible with ads, what to do?? its making very bad impresion on my UI,and as u know whenever user select any listview item,that disaappering beacuse of refreshing listview.

**Comment by kot331107** [comment]
What Android API do you use? Do you use exactly ListView or RecyclerView? We don't experience such a behavior in sampleapp.

**Comment by sid9890** [comment]
i am using listview,it not happening in your sample code,maybe it shows local item in listview,but its happening in my real time app it loads item from server
    first it loads my feeds in listview with blank advertisement position nd then suddenly it get refresh/recycle and it loads ads in specified space.
any solution???

**Comment by kot331107** [comment]
@sid9890 try to wrap ad with simple FrameLayout or a CardView. See https://github.com/clockbyte/admobadapter/wiki/Cookbook#in-case-you-want-to-wrap-your-ad-blocks-into-a-viewgroup-cardview-framelayout-etc for instance
