### ISSUE TITLE
Unable to set user's admobReleaseUnitId. Adapter use HARDCODED value of AdMob ad unit id.

### ISSUE THREAD

**Issue by bizire** [clockbyte/admobadapter#79]
`adapterWrapper = new AdmobAdapterWrapper(context, admobReleaseUnitId);`

**admobReleaseUnitId** - never used in code, because in method init() **Collection(String) admobReleaseUnitIds** never used:

```
private void init(Context context, Collection<String> admobReleaseUnitIds, String[] testDevicesId, EnumSet<EAdType> adTypesToShow){
        setNoOfDataBetweenAds(DEFAULT_NO_OF_DATA_BETWEEN_ADS);
        setLimitOfAds(DEFAULT_LIMIT_OF_ADS);
        setContentAdsLayoutContext(ContentAdLayoutContext.getDefault());
        setInstallAdsLayoutContext(InstallAppAdLayoutContext.getDefault());
        mContext = context;
        adFetcher = new AdmobFetcher();
        if(testDevicesId!=null)
            for (String testId: testDevicesId)
                adFetcher.addTestDeviceId(testId);
        adFetcher.setAdTypeToFetch(adTypesToShow == null || adTypesToShow.isEmpty()
                ?  EnumSet.allOf(EAdType.class): adTypesToShow);
        adFetcher.addListener(this);
        // Start prefetching ads
        adFetcher.prefetchAds(context.getApplicationContext());
    }
```

 Instead of that adapter use hardcoded values of **test_admob_unit_id**
```
<resources>
    <string name="app_name">admobadapter</string>
    <string name="test_admob_unit_id">ca-app-pub-3940256099942544/3986624511</string>
    <string name="test_admob_express_unit_id">ca-app-pub-3940256099942544/1072772517</string>
</resources>
```

Please, add capability to set users AdMob unit ID.

**Comment by mzdhr** [comment]
same here!

**Comment by kot331107** [comment]
Guyz, we don't support Admob Native Advanced right now since it is in beta for now! The code in our lib is just a sort of draft. We are going to refactor it after Native Advanced will be released.

**Comment by JohNan** [comment]
@kot331107 even though you write it in the readme? 

Anyhay, uou can use my fork if you want to be able to set it. I only added support for one Unit Id per adapter. 
Fork: https://github.com/JohNan/admobadapter
Use jitpack: https://jitpack.io/#JohNan/admobadapter/master-SNAPSHOT

**Comment by kot331107** [comment]
@JohNan absolutely..even though :) glad to see that you contribute to this library. I just have no time to support Advanced Ads at the moment. I really hope I'll continue supporting this lib later.

**Comment by JohNan** [comment]
@kot331107 No problems. I also think this library would benefit from using a builder pattern instead of this growing constructor. I might have a look at that as well if I get some time over :) Thanks for a great lib.

**Comment by kot331107** [comment]
@JohNan  I've refactored wrappers for Express ads to be created with Builder pattern. Also is it OK if I get some changes from your fork via a pull request?

**Comment by kot331107** [comment]
PR was created and merged. closing it for now

**Comment by JohNan** [comment]
@kot331107 ofc! :-)
