### ISSUE TITLE
Check event no ads return? 

### ISSUE THREAD

**Issue by hoanganh2020** [clockbyte/admobadapter#8]
Hi,

You can add function to check event no ads return?

public void onAdLoaded();
public void onAdFailedToLoad(int errorCode);
public void onAdOpened();
public void onAdClosed();
public void onAdLeftApplication();

Thanks!

**Comment by clockbyte** [comment]
Hi,
I'll investigate it and turn back to you with some comments, Ok?

KR!

**Comment by hoanganh2020** [comment]
I Clockbyte,

I'm waiting!

Thanks!

**Comment by mourjan** [comment]
maybe we can provide that given the new NativeExpressAd class,
this way users can specify their own custom AdListeners.
what do you think?

**Comment by kot331107** [comment]
@mourjan I guess you are right :+1: As for me the main prio is to get stable and well-documented admobadapter. Your idea is perfect to get more flexibility.

**Comment by kot331107** [comment]
@hoanganh2020 Hi,

You can see https://github.com/clockbyte/admobadapter/wiki/Cookbook#in-case-you-want-to-wrap-your-ad-blocks-into-a-viewgroup-cardview-framelayout-etc 
At the moment `NativeExpressAdViewHolder#isFailedToLoad()` is the only way to get some info on the ad block. Hope it will help you. I suppose we'll extend and improve this class further with some events and other extra-states for ads.
