### ISSUE TITLE
Custom Adsize in NativeExpressAds Not working

### ISSUE THREAD

**Issue by himanshuvirmani** [clockbyte/admobadapter#83]
Even though the size is changed by using 

`adapterWrapper = new AdmobExpressRecyclerAdapterWrapper(getContext(), testDevicesIds, new AdSize(320, 100))`

it is picking it as 

`new AdSize(AdSize.FULL_WIDTH, 150)`

resulting in 

"Not enough space to show ad."

**Comment by kot331107** [comment]
You 're right. Fixed it.
