### ISSUE TITLE
AdmobExpressRecyclerAdapterWrapper: notifyItem*(int position, ...) methods not working correctly.

### ISSUE THREAD

**Issue by Thomas-Vos** [clockbyte/admobadapter#85]
Hello, I really like your library and would like to use it for my RecyclerView. However, the `notifyItem*(int position, ...)` methods don't work correctly for me.

**Example:**
1. An AdMob ad is located at position 2.
2. Now call the method `mAdapter.notifyItemChanged(5);`
3. The adapter wrapper refreshes position **4** instead. This is wrong and should be **5**, right?

I think something is going wrong at the translation of the position if there are ads loaded. (see code [here](https://github.com/clockbyte/admobadapter/blob/master/admobadapter/src/main/java/com/clockbyte/admobadapter/expressads/AdmobExpressRecyclerAdapterWrapper.java#L55L82)). Could you look into this, please?

**Comment by Thomas-Vos** [comment]
@kot331107 Could you help me with this, please?

**Comment by kot331107** [comment]
@Thomas-Vos I'll check

**Comment by Thomas-Vos** [comment]
@kot331107 Thanks for your reply. Actually, `mAdapter` is the original adapter and NOT the adapter wrapper. I think [this is the part where it goes wrong](https://github.com/clockbyte/admobadapter/blob/master/admobadapter/src/main/java/com/clockbyte/admobadapter/expressads/AdmobExpressRecyclerAdapterWrapper.java#L61L80) (see line 61-80). It just redirects the calls from the original adapter to the adapter wrapper, without taking the ad position(s) into account.

Anyway, I decided to remove ads from my app, so I won't be needing your library anymore. However, this (bug) might be helpful for other people. (I can't reopen this issue).

Thanks for your help,
Thomas

**Comment by kot331107** [comment]
@Thomas-Vos Sure. However you can try the updated **sampleapp** in **experimental**. I call `mAdapter.notifyItemChanged(5);` and then I get exactly the 5th index updated. I have just checked it by debugging [that lines](https://github.com/clockbyte/admobadapter/blob/master/admobadapter/src/main/java/com/clockbyte/admobadapter/expressads/AdmobExpressRecyclerAdapterWrapper.java#L61L69).
