### ISSUE TITLE
cannot install via gradle

### ISSUE THREAD

**Issue by setiawanfredy** [clockbyte/admobadapter#86]
hello, im newbie on android studio.
i try to install via gradle but its always fail
this is the event log:

Information:Gradle tasks [:app:generateDebugSources, :app:generateDebugAndroidTestSources, :app:mockableAndroidJar, :app:prepareDebugUnitTestDependencies]
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.0.0-alpha1) from [com.android.support:appcompat-v7:26.0.0-alpha1] AndroidManifest.xml:27:9-38
	is also present at [com.android.support:recyclerview-v7:25.3.1] AndroidManifest.xml:24:9-31 value=(25.3.1).
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:25:5-27:41 to override.
Information:BUILD FAILED
Information:Total time: 5.88 secs
Information:1 error
Information:0 warnings
Information:See complete output in console

**Comment by kot331107** [comment]
@setiawanfredy Just try to add a string `tools:replace = "android:value"` to your **application** tag in the app's manifest. Like this
` <application
        android:name=".ApplicationEx_"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/AppTheme"
        tools:replace="android:value">`

Do it for all such errors you'll get (there could be a bunch of such errors in sequence).

**Comment by kot331107** [comment]
@setiawanfredy also try to add `tools:replace="android:value"` to the `<manifest>` element instead of `<application>`
