### ISSUE TITLE
Does it reuse loaded AdRequests?

### ISSUE THREAD

**Issue by Marty** [clockbyte/admobadapter#90]
Hi,
does admobadapter reuse already loaded AdRequests or does it load a new one every time an ad is displayed?
If not, this could lower the click ratio by quite a bit, or am I wrong?
Greetings

**Comment by kot331107** [comment]
@Marty Hi,
You are talking about Native ads (not native express), aren't you? Then the answer is: yes it does. [This class ](https://github.com/clockbyte/admobadapter/blob/master/admobadapter/src/main/java/com/clockbyte/admobadapter/AdmobFetcher.java)is used for fetching and reusing of already loaded AdRequests.

**Comment by Marty** [comment]
Thanks for the answer and pointing out the correct file!

**Comment by kot331107** [comment]
Welcome!
