### ISSUE TITLE
How to add multiple ad unit IDs in AdmobExpressRecyclerAdapterWrapper

### ISSUE THREAD

**Issue by Shajeel-Afzal** [clockbyte/admobadapter#91]
I am using `1.3.1` version of the library and I want to add multiple ad units IDs in `AdmobExpressRecyclerAdapterWrapper` so that a different ad is loaded each time in the list. Is it possible? I don't want to update the library to 1.4.5 for now because I am facing issues with 26.0.1 support library.

**Comment by kot331107** [comment]
@Shajeel-Afzal You could try to update to 1.4.1, it used the 25.3.1 support lib. However, yes, it supports  multiple ad ids since **1.3.1**, kindly check [here](https://github.com/clockbyte/admobadapter/wiki/Cookbook#in-case-you-want-to-use-a-multiple-unit-ids)

**Comment by Shajeel-Afzal** [comment]
Thank you so much for the quick update.

**Comment by kot331107** [comment]
@Shajeel-Afzal you welcome! please also check [releases info](https://github.com/clockbyte/admobadapter/releases). There were much changes and major/minor fixes since 1.3.1 so I would strongly advice you to go for **1.4.1**

**Comment by Shajeel-Afzal** [comment]
One quick question @kot331107, the ad container should be removed/hidden if ad fails to load for some reason. Are you going to add support for that or is the library handles that?

**Comment by kot331107** [comment]
@Shajeel-Afzal Yeah it handles it itself. But there was a fix in 1.4.5 concerning this feature in the Express Recycler Wrapper. So maybe it is the best option for you to clone the latest code from the **master** branch locally and then change all **26** to **25** versions in build.gradle (build tools, compile, target and all libs).

**Comment by Shajeel-Afzal** [comment]
Super Awesome.
