### ISSUE TITLE
I have a question.

### ISSUE THREAD

**Issue by gaxfor** [clockbyte/admobadapter#93]
When does NativeExpressAdView's id initialize?
In addition, the following error will continue to occur.

No fill from ad server.
Failed to load ad: 3
com.clockbyte.admobadapter.sampleapp I/com.clockbyte.admobadapter.expressads.AdmobFetcherExpress: onAdFailedToLoad 3

**Comment by kot331107** [comment]
@gaxfor Please check https://stackoverflow.com/questions/33566485/failed-to-load-ad-3. Seems everything is OK with your unit id. There's simply no suitable ads for your options (check your mediation options in Admob, or maybe you've set too high ECPM floor level). Sometimes I get the same.

**Comment by gaxfor** [comment]
At what point should the NativeExpressAdView's id (test_admob_express_unit_id) be initialized?

**Comment by kot331107** [comment]
@gaxfor Absolutely correct, if you aren't going to use multiple unit ids.
