### ISSUE TITLE
HOW CAN I ADD MY OWN AD ID IN THIS LIB?

### ISSUE THREAD

**Issue by chiragthummar** [clockbyte/admobadapter#95]
how to replace test id with original ad id?

**Comment by kot331107** [comment]
@chiragthummar 1. What adapter do you use exactly?
2. why do you CAPSing? lol

**Comment by chiragthummar** [comment]
well ,i am using recylerview express adapter for listing

**Comment by kot331107** [comment]
@chiragthummar so kindly use [the following ctor](https://github.com/clockbyte/admobadapter/blob/v1.4.1/admobadapter/src/main/java/com/clockbyte/admobadapter/expressads/AdmobExpressRecyclerAdapterWrapper.java#L255) passing your ad unit id in the parameter **admobReleaseUnitId**

**Comment by chiragthummar** [comment]
thanks for answer.

**Comment by kot331107** [comment]
welcome!
