### ISSUE TITLE
Error:(3) Error retrieving parent for item: No resource found that matches the given name....

### ISSUE THREAD

**Issue by anushree94** [clockbyte/admobadapter#96]
Added this despendency: compile 'com.github.clockbyte:admobadapter:1.4.5' in my gradle file.
Sync now generates a list of errors. Attaching a screenshot of the errors. Any help will be appreciated. Thanks in advance.
![image](https://user-images.githubusercontent.com/18436615/30951625-ac1359ea-a441-11e7-9e83-b43964e05df9.png)

**Comment by mkhazov** [comment]
`compileSdkVersion 26` will help you.

**Comment by kot331107** [comment]
@anushree94 solved already?
