### ISSUE TITLE
Where are you specifying the Native Advanced Ad IDs?

### ISSUE THREAD

**Issue by Shajeel-Afzal** [clockbyte/admobadapter#99]
Hi, 

I am trying to implement Native Advanced Ads by following the sample app code here: https://github.com/clockbyte/admobadapter/blob/master/sampleapp/src/main/java/com/clockbyte/admobadapter/sampleapp/MainActivity_RecyclerView.java 

and in the Recipe here, But I don't see that where are you specifying the Native Advanced Ad IDs. 

Does Advanced Ads work differently?

Can you please correct me?

**Comment by Shajeel-Afzal** [comment]
Okay, I see your comment that says use different ctor when releasing the app. 
//when you'll be ready for release please use another ctor with admobReleaseUnitId instead.

**Comment by timemake** [comment]
Hi, Thanks for very good tutorial! I have two questions for you. 1) I'm planning to show the native advanced app in alert dialog so I would like to display the ad on one simple view. 2) It seems like the ad size is too big to show in the ListView. Are you able to change the ad size? Thanks for your help in advance!
